'use strict';
const E=window.ResearchEngine;
const METHODS=[
 {id:'MM',name:'MM',kind:'景氣與產業傳導',q:'需求改善，能傳到這家公司嗎？',data:'產業需求、庫存、利率與公司營收',counter:'景氣改善，但接單、市占或利潤下降',attribution:'系統套用框架；有原文才可歸因 MM',stage:'可半自動'},
 {id:'GOOAYE',name:'股癌',kind:'論點與催化事件',q:'節目論點與本股的關聯成立嗎？',data:'節目期數、日期、逐字稿與時間碼',counter:'時程延後、競爭優勢減弱或作者修正觀點',attribution:'原文缺失就資料不足，不猜作者立場',stage:'需要原文'},
 {id:'MANNY',name:'曼報',kind:'技術到商業化',q:'技術優勢如何轉成獲利？',data:'文章原文、客戶採用及產品經濟性',counter:'客戶未採用、定價下降或替代方案更好',attribution:'付費全文須合法取得並可定位',stage:'需要原文'},
 {id:'MARKS',name:'Marks',kind:'價格與風險補償',q:'現價需要多樂觀的未來？',data:'同期間估值情境、負債與信用風險',counter:'只有最樂觀情境才撐得住價格',attribution:'風險立場與股價方向分欄，不能直接互換',stage:'可半自動'},
 {id:'MANUS',name:'MANUS',kind:'證據整理流程',q:'支持與反證能否重現？',data:'論點、獨立證據、反證與驗證事件',counter:'關鍵主張沒有可查來源，或反證成立',attribution:'工作台內部流程，不多算一票利多',stage:'適合自動整理'},
 {id:'MINERVINI',name:'Minervini',kind:'成長與價格趨勢',q:'成長與可重現的趨勢結構一致嗎？',data:'足夠歷史行情、相對強弱及核定模板',counter:'突破失敗、結構失效或基本成長轉弱',attribution:'尚未實作完整 SEPA／VCP 辨識',stage:'規格待核定'},
 {id:'BUFFETT',name:'巴菲特／芒格',kind:'長期企業價值',q:'長期現金產生能力值得持有嗎？',data:'多年現金流、競爭優勢與資本配置',counter:'優勢流失、負債上升或資本報酬惡化',attribution:'企業品質研究角度，不代表當期推薦',stage:'需要長期研究'}
];
const GATES=[['identity','公司與市場身分'],['core','核心資料完整且可比'],['thesis','企業／事件論點有支持'],['valuation','估值與風險補償合理'],['trigger','策略預設觸發已成立']];
const STATUSES=['條件符合','等待條件','風險升高','資料不足'];
const COLOR={'條件符合':'good','等待條件':'wait','風險升高':'risk','資料不足':'neutral','待確認':'neutral','已暫停':'neutral','已移除':'neutral'};
const KEY='fruit-stock-workbench-v2-local';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v===null?'—':Number(v).toLocaleString('zh-TW',{maximumFractionDigits:2});
const tag=(s,c)=>`<span class="tag ${c||COLOR[s]||'neutral'}">${esc(s)}</span>`;
const when=()=>new Date().toLocaleString('zh-TW',{timeZone:'Asia/Taipei',hour12:false});
const makeRecord=(e,demo=false)=>({id:`${e.exchange}:${e.ticker}`,name:e.name,ticker:e.ticker,exchange:e.exchange,asset:e.asset,demo,paused:false,removed:false,horizon:'event',config:{mode:'auto',selected:[]},revision:1,reportVersion:1,reportRevision:1,confirmedKey:null,thesis:'尚未建立可查證的投資論點。',note:'',gates:{identity:true,core:null,thesis:null,valuation:null,trigger:null},risk:false,evidence:[],history:[{title:'建立研究卡',detail:'公司身分來自目錄快照；行情、財務及研究結論尚未取得。'}],scenario:{eps:['','',''],pe:['','','']},organizedAt:null});
const demos=[
 ['DEMO01','長期品質企業','公司品質良好，但價格尚未提供足夠補償。','等待條件',{identity:true,core:true,thesis:true,valuation:false,trigger:false},'等候估值回到合理情境，或獲利證據上修。'],
 ['DEMO02','成長轉折企業','假設成長與估值條件已驗證，事件觸發也已成立。','條件符合',{identity:true,core:true,thesis:true,valuation:true,trigger:true},'持續核對下一次營收與毛利率，避免假設過期。'],
 ['DEMO03','週期設備企業','假設訂單延後的反證成立；現金流資料仍有缺口。','風險升高',{identity:true,core:null,thesis:false,valuation:null,trigger:false},'先核對訂單與現金承受力，保留財務缺口提示。'],
 ['DEMO04','新產品企業','題材有潛力，但尚未取得客戶採用與財务驗證。','資料不足',{identity:true,core:null,thesis:null,valuation:null,trigger:null},'補上客戶採用、公告財務及原始論點來源。']
].map(([ticker,name,thesis,status,gates,next])=>({...makeRecord({ticker,name,exchange:'虛構案例',asset:'個股'},true),thesis,gates,next,risk:status==='風險升高',scenario:{eps:[8,10,12],pe:[15,18,20]},history:[{title:'載入假設案例',detail:'所有條件與數字均為介面示範，不對應真實公司。'}],evidence:status==='資料不足'?[]:[{type:'假設資料',date:'2026-10-05',claim:'假設財務與產業資料支持成長；此段只示範證據卡版型。',url:''}]}));
let storageError=false,local=[];
try{const s=JSON.parse(localStorage.getItem(KEY)||'[]');if(Array.isArray(s))local=s.filter(r=>r&&typeof r.id==='string'&&typeof r.name==='string'&&r.gates&&r.config&&Array.isArray(r.config.selected)&&Array.isArray(r.history)&&Array.isArray(r.evidence)&&r.scenario&&Array.isArray(r.scenario.eps)&&Array.isArray(r.scenario.pe));}catch{storageError=true;}
let mode=local.length?'mine':'demo',view='workspace',selected=(local[0]||demos[0]).id,tab='overview',filter='全部',query='',busy=false,progressText='',progress=0;
let toastTimer;
function toast(s){const x=document.querySelector('#toast');x.textContent=s;x.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>x.style.display='none',5000);}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(local));storageError=false;}catch{storageError=true;toast('瀏覽器無法保存，請先匯出研究備份。');}}
function rows(){return mode==='demo'?demos:local;}
function current(){return rows().find(r=>r.id===selected);}
function changeRecord(n){const list=rows(),i=list.findIndex(r=>r.id===n.id);if(i>=0)list[i]=n;if(!n.demo)persist();}
function invalidate(r,title,detail){r.revision+=1;r.confirmedKey=null;r.history.unshift({title,detail:`${when()} · ${detail}`});}
function key(r){return `${r.revision}:${r.reportVersion}`;}
function methods(r){return r.config.mode==='auto'?E.methodsFor(r.asset,r.horizon):r.config.selected;}
function missing(r){return GATES.filter(([k])=>r.gates[k]===null||r.gates[k]===undefined).length;}
function setView(v){view=v;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));document.querySelector('#page-title').textContent={workspace:'研究工作台',methods:'七法與適用性',feasibility:'可行性與進度'}[v];render();}
function render(){document.querySelector('#view-root').innerHTML=view==='workspace'?workspace():view==='methods'?methodLibrary():feasibility();if(storageError)document.querySelector('#view-root').insertAdjacentHTML('afterbegin','<p class="error">本機保存不可用或檔案格式不相容。請匯出目前研究，避免關閉後遺失。</p>');}
function workspace(){
 const list=rows(),active=list.filter(r=>!r.removed&&!r.paused),counts=STATUSES.map(s=>active.filter(r=>E.classify(r)===s||(s==='資料不足'&&E.classify(r)==='待確認')).length);
 const visible=list.filter(r=>filter==='已移除'?r.removed:filter==='已暫停'?r.paused&&!r.removed:!r.removed&&!r.paused&&(filter==='全部'||E.classify(r)===filter||(filter==='資料不足'&&E.classify(r)==='待確認')));
 if(!visible.some(r=>r.id===selected))selected=visible[0]?.id||null;
 return `<div class="modebar"><div class="segments" aria-label="資料模式"><button data-action="mode" data-value="mine" class="${mode==='mine'?'active':''}" aria-pressed="${mode==='mine'}">我的研究 <small>${local.filter(r=>!r.removed).length}</small></button><button data-action="mode" data-value="demo" class="${mode==='demo'?'active':''}" aria-pressed="${mode==='demo'}">看假設案例</button></div><p class="muted">${mode==='demo'?'所有案例皆虛構 · 不對應實際股價或公司':'筆記與設定保存在此瀏覽器 · 不會寫入公開 GitHub'}</p></div>
 <div class="stats">${STATUSES.map((s,i)=>`<button class="stat ${filter===s?'active':''}" data-action="filter" data-value="${s}" aria-pressed="${filter===s}"><div><div class="label">${s}</div><div class="num">${counts[i]} <small>檔</small></div><div class="desc">${['可進一步研究','等估值或事件確認','先處理反證','先補資料缺口'][i]}</div></div><span class="stat-icon">${['✓','◷','!','…'][i]}</span></button>`).join('')}</div>
 <div class="workspace"><section class="panel" aria-label="研究清單"><div class="panel-head"><div class="panel-title"><h3>研究清單</h3><button class="button small" data-action="filter" data-value="全部">全部</button></div><label class="fine" for="company-search">輸入公司名稱或代號即可新增</label><div class="searchbox"><input id="company-search" placeholder="例如：研華、聯發科、0050" value="${esc(query)}" autocomplete="off" aria-controls="search-results"><div id="search-results">${searchResults()}</div></div><div class="list-tools"><select id="list-filter" aria-label="研究狀態篩選">${['全部',...STATUSES,'已暫停','已移除'].map(s=>`<option ${filter===s?'selected':''}>${s}</option>`).join('')}</select></div><p class="fine" style="margin-top:9px">目錄：${window.COMPANY_DIRECTORY.entries.length.toLocaleString()} 筆 · 2026-10-05 快照</p></div><div class="stock-list">${visible.length?visible.map(r=>stockRow(r)).join(''):`<div class="empty">${mode==='mine'&&filter==='全部'?'先搜尋一家公司，<br>建立你的第一張研究卡。':'目前沒有此類研究。'}</div>`}</div></section>
 <section class="panel" aria-label="個股研究">${current()?detail(current()):'<div class="empty"><h2>從一個研究問題開始</h2><p style="margin-top:14px">搜尋公司名稱就能建立卡片，<br>再逐步補上論點、來源和失效條件。</p><button class="button" style="margin-top:22px" data-action="mode" data-value="demo">先看四種假設案例</button></div>'}</section></div>`;
}
function searchResults(){if(!query.trim())return '';const found=E.search(window.COMPANY_DIRECTORY.entries,query);return `<div class="search-results">${found.length?found.map(e=>`<button class="search-result" data-action="add" data-value="${esc(e.exchange+':'+e.ticker)}"><b>${esc(e.name)}</b> ${esc(e.ticker)}<small>${esc(e.exchange)} · ${esc(e.fullName)} · 加入本機研究</small></button>`).join(''):'<div class="empty">目錄中沒有找到。請換名稱或代號；不猜測公司身分。</div>'}</div>`;}
function stockRow(r){return `<button class="stock-row ${r.id===selected?'active':''}" data-action="select" data-value="${esc(r.id)}" aria-pressed="${r.id===selected}"><div class="stock-top"><span class="stock-name">${esc(r.name)}</span>${r.demo?'<small class="fine">假設</small>':''}</div><div class="stock-code">${esc(r.ticker)} · ${esc(r.exchange)}</div><div class="stock-bottom">${tag(E.classify(r))}<small>${missing(r)?`${missing(r)} 項缺口`:'主要門檻已評估'}</small></div></button>`;}
function detail(r){const disabled=busy||r.paused||r.removed;return `<div class="detail-header"><div class="detail-heading"><div><div class="detail-title">${esc(r.name)}</div><div class="detail-sub">${esc(r.ticker)} · ${esc(r.asset)} · ${r.demo?'虛構研究案例':'公司目錄快照，非即時身分查核'}</div></div><div class="mini-actions">${r.removed?'<button class="button small" data-action="restore">復原</button>':`<button class="button small" data-action="pause" ${busy?'disabled':''}>${r.paused?'恢復研究':'暫停'}</button><button class="button small danger" data-action="remove" ${busy?'disabled':''}>移除</button>`}</div></div><p class="thesis">${esc(r.thesis)}</p>${r.demo?'<div class="proof">案例、證據與 EPS／PE 都是假設，只用來驗證介面與計算。</div>':''}</div>
 <div class="tabbar" role="tablist" aria-label="研究內容">${[['overview','判讀總覽'],['evidence','證據與反證'],['methods','分析法'],['valuation','估值試算'],['history','版本紀錄']].map(([id,label])=>`<button role="tab" aria-selected="${tab===id}" data-action="tab" data-value="${id}" class="${tab===id?'active':''}">${label}</button>`).join('')}</div>
 ${busy?`<div class="progressbox" role="status"><span class="muted">${esc(progressText)}</span><progress max="100" value="${progress}"></progress></div>`:''}
 <div class="detail-body" role="tabpanel">${({overview:overview,evidence:evidenceView,methods:methodView,valuation:valuationView,history:historyView}[tab])(r)}</div>
 <div class="detail-footer"><div><p>${r.confirmedKey===key(r)?'已確認已閱此本機版本':'尚未確認此版本'} · R${r.reportVersion} / M${r.revision}</p><p class="fine">Notion：尚未接入，不會排入同步</p></div><div class="mini-actions"><button class="button" data-action="rebuild" ${disabled?'disabled':''}>${busy?'整理中…':'整理本機研究'}</button><button class="button primary" data-action="confirm" ${disabled||r.reportRevision!==r.revision||r.confirmedKey===key(r)?'disabled':''}>確認已閱</button></div></div>`;}
function overview(r){const status=E.classify(r);return `<div class="decision"><div class="decision-main"><span class="eyebrow">本次判讀 ${r.demo?'· 假設案例':'· 資料門檻檢查'}</span><h2>${status}</h2><p>${r.risk?'反證优先處理，其他資料缺口仍須補齊。':status==='條件符合'?'僅表示本案例預設研究條件通過，不代表買進指令。':status==='等待條件'?'企業論點與目前價格分開看，等條件改變再評估。':'行情、核心財務或條件依據不足，暫不產生買賣區間。'}</p></div><div class="decision-side"><div class="fact"><span>行情資料日</span><b>${r.demo?'未使用實際行情':'尚未取得'}</b></div><div class="fact"><span>核心資料</span><b>${r.gates.core===true?'假設齊備':'尚有缺口'}</b></div><div class="fact"><span>研究版本</span><b>R${r.reportVersion} / M${r.revision}</b></div></div></div>
 <div class="section-title"><h3>五道研究門檻</h3><span class="fine">逐項檢查，不以總分抵銷</span></div>${GATES.map(([k,l],i)=>`<div class="gate"><div class="gate-label"><span class="gate-number">${i+1}</span><span>${l}</span></div>${tag(r.gates[k]===true?'成立':r.gates[k]===false?'未成立':'未知',r.gates[k]===true?'good':r.gates[k]===false?'wait':'neutral')}</div>`).join('')}
 <div class="next-step"><strong>下一步要確認什麼？</strong>${esc(r.next||'取得最新已完成交易日行情、可比財務與原始論點。現有筆記可先整理，不會自動轉成已驗證資料。')}</div>${r.reportRevision!==r.revision?'<div class="info">設定或筆記已變更。請按「整理本機研究」產生新版本，再確認已閱。</div>':''}`;}
function evidenceView(r){return `<div class="section-title"><h3>可追溯的研究依據</h3>${tag(`${r.evidence.length} 筆`,'neutral')}</div><p class="muted">保留原始來源、日期與定位。同一公告的轉載不增加獨立證據數。</p>
 <div style="margin-top:18px">${r.evidence.length?r.evidence.map(x=>`<article class="evidence-item"><div class="split">${tag(x.type,x.type==='反證'?'risk':'neutral')}<small class="muted">${esc(x.date||'日期待補')}</small></div><p>${esc(x.claim)}</p>${safeURL(x.url)?`<a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">開啟原始來源 ↗</a>`:'<span class="fine">無外部來源；不能視為已查證資料。</span>'}</article>`).join(''):'<div class="empty">目前沒有原始證據，留白比猜測可靠。</div>'}</div>
 <details><summary style="cursor:pointer;font-size:15px">新增來源筆記</summary><form id="evidence-form"><div class="form-grid"><label class="field">證據類型<select name="type"><option>支持論點</option><option>反證</option><option>自行假設</option></select></label><label class="field">資料發布日<input type="date" name="date" required></label><label class="field full">來源網址<input type="url" name="url" placeholder="https://…" required></label><label class="field full">主張與原文定位<textarea name="claim" placeholder="例如：第 6 頁／12:30，支持或反對哪個論點？" maxlength="2000" required></textarea></label></div><button class="button" ${r.paused||r.removed||busy?'disabled':''}>保存來源筆記</button><p class="fine" style="margin-top:10px">人工輸入仍待查核；不會自動把資料門檻改為成立。</p></form></details>
 <form id="note-form"><div class="form-grid"><label class="field full">我的研究筆記<textarea name="note" maxlength="5000" placeholder="寫下核心論點、失效條件、下次驗證事件…">${esc(r.note)}</textarea></label></div><button class="button" ${r.paused||r.removed||busy?'disabled':''}>保存筆記</button></form>`;}
function methodView(r){const active=methods(r);return `<form id="method-form"><div class="form-grid"><label class="field">選用方式<select name="mode" id="method-mode"><option value="auto" ${r.config.mode==='auto'?'selected':''}>依研究目的自動建議</option><option value="manual" ${r.config.mode==='manual'?'selected':''}>由我手動選擇</option></select></label><label class="field">研究目的<select name="horizon" id="horizon"><option value="event" ${r.horizon==='event'?'selected':''}>事件／成長研究</option><option value="long" ${r.horizon==='long'?'selected':''}>長期企業價值</option><option value="trend" ${r.horizon==='trend'?'selected':''}>成長與趨勢</option></select></label></div>
 <p class="muted">${r.asset==='ETF'?'ETF 預設 MM＋Marks＋MANUS。個股 EPS 估值不直接套用 ETF。':'自動建議只決定研究視角；不代表資料齊備或方法已驗證。'}</p>
 <div class="method-list">${METHODS.map(m=>`<div class="method-card ${active.includes(m.id)?'selected':''}"><label><input type="checkbox" name="method" value="${m.id}" ${active.includes(m.id)?'checked':''} ${r.config.mode==='auto'?'disabled':''}>${m.name}</label><p>${m.kind}</p><span class="tag neutral">${r.demo?demoDirection(m,r):'資料不足／未評估'}</span><div class="meta" style="margin-top:9px">${m.attribution}</div></div>`).join('')}</div>
 <button class="button primary" ${r.paused||r.removed||busy?'disabled':''}>保存分析法設定</button><div class="info">Marks 顯示風險立場，MANUS 整理證據。兩者都不當作額外看多票數。變更設定會解除舊版本的已閱確認。</div></form>`;}
function demoDirection(m,r){if(['GOOAYE','MANNY'].includes(m.id))return '資料不足：未取得原文';if(m.id==='MINERVINI')return '未實作完整模板';if(m.id==='BUFFETT')return '長期證據待補';if(m.id==='MANUS')return '整理分歧，不計票';if(m.id==='MARKS')return r.gates.valuation===false?'假設立場：偏防守':'風險補償待逐項核對';return r.gates.thesis===true?'假設需求改善':'傳導關係待查';}
function valuationView(r){if(r.asset==='ETF')return `<h3>ETF 使用獨立的研究框架</h3><p class="lead">先核對追蹤指數、持股集中度、費用、追蹤差異、流動性及折溢價。配息率不等於總報酬。</p><div class="next-step">${tag('資料不足')}<p style="margin-top:12px">ETF 資料接入後，才顯示對應的淨值與風險分析。此頁不使用公司 EPS × PE。</p></div>`;
 return `<div class="section-title"><h3>三情境假設試算</h3>${tag('自行假設','wait')}</div><p class="muted">所有數值是可修改的假設。試算結果不會更動研究結論，也不代表目標價。</p><form id="scenario-form"><div class="table-wrap" style="margin-top:20px"><table><thead><tr><th>情境</th><th>同年度 EPS</th><th>PE 倍數</th><th>情境參考價</th></tr></thead><tbody>${['保守','基準','樂觀'].map((s,i)=>`<tr><td>${s}</td><td><input aria-label="${s} EPS" name="eps${i}" type="number" step="any" value="${esc(r.scenario.eps[i])}" placeholder="—"></td><td><input aria-label="${s} PE" name="pe${i}" type="number" step="any" value="${esc(r.scenario.pe[i])}" placeholder="—"></td><td><output id="price${i}" class="price-out">${fmt(E.price(r.scenario.eps[i],r.scenario.pe[i]))}</output></td></tr>`).join('')}</tbody></table></div><div id="scenario-chart">${scenarioChart(r.scenario)}</div><div class="info">計算：EPS × PE。空值、非正 EPS 或非正 PE 不出價格。未使用機率加權，也不取三個價格的平均。</div><button class="button" ${r.paused||r.removed||busy?'disabled':''}>保存這組假設</button></form>
 <details style="margin-top:25px"><summary style="cursor:pointer">報酬風險比算式</summary><form id="rr-form"><div class="form-grid"><label class="field">候選進場 E<input name="entry" type="number" step="any" placeholder="100"></label><label class="field">失效参考 S<input name="stop" type="number" step="any" placeholder="92"></label><label class="field">對應情境 T<input name="target" type="number" step="any" placeholder="116"></label><label class="field">毛 RR<output id="rr-output" style="font-size:24px">—</output></label></div><p class="fine">此處只驗算 (T−E)/(E−S)，須 0 &lt; S &lt; E &lt; T；真實研究仍須同期間依據，另計費用、稅與滑價，RR 不是勝率。</p></form></details>`;}
function scenarioChart(s){const prices=s.eps.map((e,i)=>E.price(e,s.pe[i])),max=Math.max(1,...prices.filter(x=>x!==null));return `<div class="scenario-chart"><p>假設情境比較 <span class="fine">· 無即時股價比較線</span></p>${['保守','基準','樂觀'].map((n,i)=>`<div class="scenario-row"><span>${n}</span><div><div class="scenario-bar" style="width:${prices[i]===null?0:100*prices[i]/max}%"></div></div><b>${fmt(prices[i])}</b></div>`).join('')}</div>`;}
function historyView(r){return `<h3>每次判斷都留下版本</h3><div class="info">已閱確認綁定 R${r.reportVersion} / M${r.revision}。新資料、方法或筆記變更後，須整理新版本再確認。確認僅記錄本機，不等於 Notion 已同步。</div><div class="history">${r.history.slice(0,25).map(h=>`<div class="history-item"><strong>${esc(h.title)}</strong><p>${esc(h.detail)}</p></div>`).join('')}</div>`;}
function methodLibrary(){return `<p class="lead">先辨認這是投資理論、研究來源，還是整理流程。七種角度各自回答不同問題，整合時保留分歧。</p><div class="map-grid"><article class="map-card"><div class="step">01 / 公司</div><h3>生意是否改善？</h3><p>從需求、獲利品質到長期競爭力。</p><ul><li>MM：總經傳導</li><li>曼報：商業化</li><li>巴菲特／芒格：企業品質</li></ul></article><article class="map-card"><div class="step">02 / 價格</div><h3>價格反映多少期待？</h3><p>將價值範圍、風險與走勢分開。</p><ul><li>Marks：風險補償</li><li>Minervini：成長與趨勢</li><li>三情境：檢查假設敏感度</li></ul></article><article class="map-card"><div class="step">03 / 驗證</div><h3>什麼證據會改變判斷？</h3><p>把來源論點轉成可追蹤事件。</p><ul><li>股癌：催化事件與原論點</li><li>MANUS：證據與反證鏈</li><li>版本紀錄：保留轉向原因</li></ul></article></div><div class="method-library">${METHODS.map(m=>`<article><div class="split"><h3>${m.name} <span class="fine">${m.kind}</span></h3>${tag(m.stage,'blue')}</div><p><b>研究問題</b>　${m.q}</p><p><b>必要資料</b>　${m.data}</p><p><b>反證條件</b>　${m.counter}</p><div class="info">${m.attribution}</div></article>`).join('')}</div><section class="panel full-panel"><h3>選法建議</h3><div class="table-wrap" style="margin-top:18px"><table><thead><tr><th>研究目的</th><th>建議組合</th><th>先檢查的缺口</th></tr></thead><tbody><tr><td>事件／成長</td><td>MM＋股癌＋曼報＋Marks＋MANUS</td><td>原文、公司受惠關係與催化時程</td></tr><tr><td>長期企業價值</td><td>MM＋Marks＋MANUS＋巴菲特／芒格</td><td>多年現金流、資本配置與價值假設</td></tr><tr><td>成長與趨勢</td><td>MM＋Marks＋MANUS＋Minervini</td><td>完整歷史行情與核定規則；未完成不判通過</td></tr><tr><td>ETF</td><td>MM＋Marks＋MANUS</td><td>持股、費用、追蹤差異、流動性與折溢價</td></tr></tbody></table></div></section>`;}
function feasibility(){return `<p class="lead">GitHub Pages 適合放研究介面。需要私密憑證、雲端保存及自動更新的工作，交給具登入驗證的後端。</p><section class="panel full-panel"><div class="section-title"><h2>這個版本做到哪裡？</h2>${tag('前端已實作','good')}</div><div class="table-wrap"><table class="roadmap-table"><thead><tr><th>功能</th><th>本版狀態</th><th>正式接入條件</th></tr></thead><tbody>${[
 ['名稱搜尋與身分目錄','已實作','1,988 筆沿用目錄快照；需持續維護更名、上市櫃與交易狀態'],['本機清單、證據、筆記、暫停／移除復原','已實作','瀏覽器保存；換裝置不會自動同步'],['七法設定與版本已閱確認','已實作','自動模式是選法建議，並未自動讀取作者原文'],['EPS × PE、RR 假設試算','已實作','試算不變成正式估值或交易區間'],['官方行情與財報自動更新','待接後端','市場日、還原口徑、失敗重試及資料來源核對'],['MM／股癌／曼報原文','部分需人工','取得可用且合法的原始內容；付費頁需有效授權'],['Notion 確認後同步','本版尚未接入','伺服器保管憑證，版本鎖定、冪等寫入與讀回'],['完整 DCF、SEPA／VCP 與全市場回測','後續研究','完整資料、明確規則與無前視偏誤驗證']
 ].map(([a,b,c])=>`<tr><td>${a}</td><td>${tag(b,b==='已實作'?'good':'neutral')}</td><td>${c}</td></tr>`).join('')}</tbody></table></div></section><div class="map-grid"><article class="map-card"><div class="step">前端 / GITHUB PAGES</div><h3>搜尋、閱讀、比較</h3><p>發布程式與公開公司目錄。你的研究筆記留在本機，不會隨網頁發布到儲存庫。</p></article><article class="map-card"><div class="step">後端 / 下一階段</div><h3>取資料與執行研究</h3><p>提供行情、財務、研究工作進度、登入與雲端保存；錯誤時保留前版日期。</p></article><article class="map-card"><div class="step">同步 / 明確確認</div><h3>鎖定版本再寫入</h3><p>先看差異、確認報告，再由工作排程寫入 Notion 並讀回。不把按下確認當作同步成功。</p></article></div><section class="panel full-panel"><h2>分階段接入</h2>${[
 ['01','先把流程用順','本機目錄、筆記、證據、七法設定與試算。這是目前 GitHub 版範圍。','本版'],['02','接上可信資料','逐市場接官方行情與財報；每個欄位保存期別、發布日與取得日。','資料串接'],['03','完成研究與確認','核對來源、比對前版、顯示實際任務進度，並建立版本確認。','研究後端'],['04','確認後同步 Notion','建立可靠佇列、失敗可重試、移除暫停檢查與讀回驗證。','同步驗收']
 ].map(([i,t,d,s])=>`<div class="milestone"><span class="phase">${i}</span><div><h3>${t}</h3><p>${d}</p></div>${tag(s,i==='01'?'good':'neutral')}</div>`).join('')}<div class="info">原工作台有獨立資料庫與每日研究流程。本頁不是後端搬遷，也尚未加入既有 07:00 同步排程。</div><p class="fine">原始參考：<a href="https://docs.github.com/en/pages/getting-started-with-github-pages/what-is-github-pages" target="_blank" rel="noopener noreferrer">GitHub Pages</a> · <a href="https://openapi.twse.com.tw/" target="_blank" rel="noopener noreferrer">TWSE OpenAPI</a> · <a href="https://data.gov.tw/dataset/25036" target="_blank" rel="noopener noreferrer">上櫃公司資料</a> · <a href="https://developers.notion.com/reference/request-limits" target="_blank" rel="noopener noreferrer">Notion API 限制</a></p></section>`;}
function safeURL(s){try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password;}catch{return false;}}
function addCompany(id){const e=window.COMPANY_DIRECTORY.entries.find(e=>`${e.exchange}:${e.ticker}`===id);if(!e)return;let r=local.find(x=>x.id===id);if(r?.removed){mode='mine';filter='已移除';selected=id;query='';render();toast('此公司已移除，請按「復原」恢復。');return;}if(!r){r=makeRecord(e);local.push(r);persist();}mode='mine';filter=r.paused?'已暫停':'全部';selected=id;query='';tab='overview';render();toast('已開啟本機研究卡；尚未取得即時行情。');}
async function rebuild(){const r=current();if(!r||busy||r.paused||r.removed)return;busy=true;try{const steps=['檢查本機公司身分與暫停狀態','整理目前選法與證據缺口','重新計算研究門檻','保存本機版本；未抓取網路資料'];for(let i=0;i<steps.length;i++){progressText=steps[i];progress=(i+1)*25;render();await new Promise(resolve=>setTimeout(resolve,170));}r.reportVersion+=1;r.reportRevision=r.revision;r.confirmedKey=null;r.organizedAt=when();r.history.unshift({title:`產生本機版本 R${r.reportVersion}`,detail:`${r.organizedAt} · 使用現有 ${r.evidence.length} 筆來源筆記，未新增任何行情或財報。`});changeRecord(r);}finally{busy=false;render();}toast('整理完成。來源日期保持原值；可確認已閱此版本。');}
function exportLocal(){const data={format:'stock-research-local-v2',exportedAt:new Date().toISOString(),directoryAsOf:window.COMPANY_DIRECTORY.asOf,records:local};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='stock-research-local.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已匯出本機研究；假設示範不包含在內。');}
document.addEventListener('click',ev=>{
 const b=ev.target.closest('button');if(!b||b.disabled)return;if(b.dataset.view){if(busy){toast('正在整理，請稍候。');return;}setView(b.dataset.view);return;}const a=b.dataset.action,v=b.dataset.value;if(!a)return;if(busy&&a!=='export'){toast('正在整理，請稍候。');return;}const r=current();
 if(a==='mode'){mode=v;filter='全部';selected=rows()[0]?.id;tab='overview';render();}
 else if(a==='filter'){filter=v;render();}
 else if(a==='select'){selected=v;tab='overview';render();}
 else if(a==='tab'){tab=v;render();}
 else if(a==='add')addCompany(v);
 else if(a==='export')exportLocal();
 else if(a==='rebuild')rebuild();
 else if(a==='pause'&&r){r.paused=!r.paused;invalidate(r,r.paused?'暫停研究':'恢復研究','僅影響本機工作台。');changeRecord(r);filter=r.paused?'已暫停':'全部';render();toast(r.paused?'已暫停。可在「已暫停」篩選恢復。':'已恢復本機研究。');}
 else if(a==='remove'&&r){r.removed=true;invalidate(r,'移除研究卡','保留歷史，可由「已移除」復原。');changeRecord(r);render();toast('已移除並保留歷史，可在「已移除」復原。');}
 else if(a==='restore'&&r){r.removed=false;invalidate(r,'復原研究卡','原有暫停狀態保留。');changeRecord(r);filter=r.paused?'已暫停':'全部';render();}
 else if(a==='confirm'&&r&&!r.paused&&!r.removed&&r.reportRevision===r.revision){r.confirmedKey=key(r);r.history.unshift({title:`確認已閱 R${r.reportVersion} / M${r.revision}`,detail:`${when()} · 本機已閱紀錄；Notion 尚未接入。`});changeRecord(r);render();toast('已記錄你看過此版本，未同步 Notion。');}
});
document.addEventListener('input',ev=>{
 if(ev.target.id==='company-search'){query=ev.target.value;document.querySelector('#search-results').innerHTML=searchResults();}
 if(ev.target.closest('#scenario-form')){const d=new FormData(document.querySelector('#scenario-form'));const s={eps:[0,1,2].map(i=>d.get('eps'+i)),pe:[0,1,2].map(i=>d.get('pe'+i))};s.eps.forEach((e,i)=>document.querySelector('#price'+i).textContent=fmt(E.price(e,s.pe[i])));document.querySelector('#scenario-chart').innerHTML=scenarioChart(s);}
 if(ev.target.closest('#rr-form')){const d=new FormData(document.querySelector('#rr-form'));document.querySelector('#rr-output').textContent=fmt(E.rr(d.get('entry'),d.get('stop'),d.get('target'),true));}
});
document.addEventListener('change',ev=>{
 if(ev.target.id==='list-filter'){if(busy){ev.target.value=filter;return;}filter=ev.target.value;render();}
 if(['method-mode','horizon'].includes(ev.target.id)){const form=document.querySelector('#method-form'),auto=form.elements.mode.value==='auto';const ids=E.methodsFor(current().asset,form.elements.horizon.value);form.querySelectorAll('[name=method]').forEach(x=>{x.disabled=auto;if(auto)x.checked=ids.includes(x.value);x.closest('.method-card').classList.toggle('selected',x.checked);});}
});
document.addEventListener('submit',ev=>{const form=ev.target;if(!['note-form','evidence-form','method-form','scenario-form'].includes(form.id))return;ev.preventDefault();let r=current();if(!r||busy||r.removed||r.paused)return;const d=new FormData(form);
 if(form.id==='note-form'){r.note=String(d.get('note')).trim();invalidate(r,'更新研究筆記','筆記屬人工研究內容，不等同已查核事實。');}
 if(form.id==='evidence-form'){const url=String(d.get('url')).trim();if(!safeURL(url)){toast('請輸入有效的 http 或 https 原始來源網址。');return;}const claim=String(d.get('claim')).trim();if(!claim){toast('請補上主張與原文定位。');return;}r.evidence.push({type:String(d.get('type')),date:String(d.get('date')),url,claim});invalidate(r,'新增來源筆記','人工記錄，尚未透過後端核實；研究門檻保持原狀。');}
 if(form.id==='method-form'){const cfg={mode:String(d.get('mode')),selected:d.get('mode')==='manual'?d.getAll('method'):[]};try{r=E.changeConfig(r,cfg);r.horizon=String(d.get('horizon'));r.history.unshift({title:'變更分析法設定',detail:`${when()} · ${methods(r).join(' / ')}；舊確認已解除。`});}catch(e){toast(e.message);return;}}
 if(form.id==='scenario-form'){r.scenario={eps:[0,1,2].map(i=>String(d.get('eps'+i))),pe:[0,1,2].map(i=>String(d.get('pe'+i)))};invalidate(r,'保存估值假設','未把假設試算轉成正式目標價或研究判讀。');}
 changeRecord(r);render();toast(r.demo?'已更新假設案例；重新整理後才能確認此版本。':'已保存本機內容；重新整理後才能確認此版本。');
});
window.addEventListener('storage',ev=>{if(ev.key===KEY)toast('其他分頁已變更研究資料，請重新整理本頁後再編輯。');});
render();
