export const domains = [
  {id:'requirements', name:'需求與任務', items:[['mission','建立產品任務與使用情境','定義負載輪廓、使用時數、海拔、環境與預期壽命。'],['markets','確認市場與合規範圍','依產品分類、銷售國家與版本制定合規矩陣。']]},
  {id:'specifications',name:'電氣規格',items:[['limits','建立完整輸入／輸出容差','包含線路、負載、漣波、過衝、待機及動態條件。'],['hold-real','量測保持時間與掉電行為','最低輸入、滿載與最低電容量下，量測輸出及控制供電。']]},
  {id:'architecture',name:'架構與效率',items:[['topology','完成拓撲與成本取捨','比較效率、功率密度、控制難度、隔離需求與 BOM。'],['eff-real','建立全範圍效率地圖','量測高低線、輕重載、待機及儀器誤差；核對損耗分布。']]},
  {id:'input',name:'輸入與 PFC',items:[['inrush','驗證突入與重啟','確認保險絲、NTC／繼電器、整流器與熱重啟。'],['pf-thd','量測 PF 與諧波','依適用產品類別、負載與標準測試；PF 假設不能取代測試。'],['active-bridge','驗證主動橋啟停與過零','TEA2209T：確認 COMP／COMP_POL 固定接法、啟動、UVLO、過零、輕載與反灌；不使用者記錄不適用理由。'],['pfc-sharing','驗證交錯 PFC 均流與母線','涵蓋相位切換、兩相容差及低負載；RRW11011 的自適應母線需逐輸入／輸出工況驗證。']]},
  {id:'powerstage',name:'功率級與諧振槽',items:[['zvs','驗證 ZVS 與換流餘裕','涵蓋容差、輸入與負載；量測死區內 Vds、電流與磁化電流。'],['stress','確認峰值與 RMS 應力','包含啟動、短路、突卸載、寄生振鈴與電容 RMS。'],['hwllc-tank','確認 HWLLC 接法與工作模式','記錄 Cr1／Cr2 接點、Lr／Lm／漏感、匝數與 VHB_SNS 網路；以各工作模式波形驗證模型，不能套用中心抽頭 FHA。']]},
  {id:'magnetics',name:'磁性元件',items:[['core','確認磁芯損耗與飽和','記錄材料、Ae、氣隙、ΔB、偏磁、頻率、溫度及批次容差。'],['winding','確認繞組損耗與絕緣','記錄線徑、層次、漏感、集膚／鄰近效應與繞製圖。']]},
  {id:'components',name:'元件與降額',items:[['derating','建立元件應力降額表','逐顆核對電壓、電流、功率、溫度與資料表條件。'],['capacitors','核對電容漣波與壽命','依原廠係數評估熱點、頻率與漣波；不得套用通用壽命公式。'],['sr-driver','核對 SR 感測與閘極相容性','RRW43110 VD 建議 −1～135 V；量測正負振鈴、OUT／VCC 與實際 MOSFET VGS、Qg。RRW40120 核對 VS 負壓、dv/dt、自舉與死區。']]},
  {id:'control',name:'控制與韌體',items:[['loop','驗證迴路與瞬態','提供 Bode、負載階躍、線路暫態、啟動及突卸載資料。'],['firmware','記錄控制器與韌體版本','含完整訂購碼、頻率限幅、死區、軟啟動、brownout、參數 CRC 與回復流程。'],['pd-transition','驗證 PD 設定與電壓轉換','RRW30120：記錄 PDO／APDO、EPR 線材、VBUS 開關與放電；驗證插拔、5～48 V 轉換、限流與突卸載。不使用者記錄不適用理由。'],['sleep-wakeup','驗證供電與待機喚醒','量測主控、驅動器及 SR 的 VCC；核對低功耗供電與驅動器建議範圍，UVLO 不能代替建議工作值。包含冷啟動、掉電、USB 拔除待機、重新接入及保護復歸。']]},
  {id:'thermal',name:'熱與機構',items:[['thermal-map','建立最差條件溫度圖','涵蓋外殼、半導體、磁性與電容；記錄風速、安裝方式與環境。'],['junction','驗證接面與熱介面','使用適當熱模型與量測方法；不可直接以封裝 θJA 推導所有機構。']]},
  {id:'emc',name:'PCB 與 EMC',items:[['layout','檢視高 di/dt 與 dv/dt 回路','確認功率迴路、回流、閘極、Kelvin、感測、Y 電容與接地。'],['emi','完成傳導／輻射預掃','保留配置、線材、LISN、接地、負載及與限值間的餘裕。']]},
  {id:'safety',name:'安規與隔離',items:[['insulation','建立絕緣與距離表','依產品標準、工作電壓、污染度、材料群組、海拔及隔離類型確認。'],['safety-tests','完成適用安規測試','依合規矩陣執行耐壓、接觸電流、接地、異常及溫升測試。']]},
  {id:'protection',name:'保護與 FMEA',items:[['protection-tests','驗證所有保護與復歸','包含 OVP、OCP、SCP、OTP、UVLO、感測開短路與重複動作。'],['fmea','完成故障模式分析','評估單點故障、嚴重度、可偵測性、措施與殘餘風險。']]},
  {id:'reliability',name:'可靠度與壽命',items:[['life','確認壽命任務條件','依負載／溫度任務分布，計算並驗證限制元件壽命。'],['environment','驗證環境與機械應力','按用途規劃溫循、濕熱、振動、跌落及包裝測試。']]},
  {id:'validation',name:'量測與驗證',items:[['instrument','確認儀器與量測不確定度','記錄校驗、頻寬、探棒、接線、共模能力與誤差。'],['dvp','完成設計驗證矩陣','每項規格需對應方法、樣本數、條件、結果、責任人与報告版本。']]},
  {id:'manufacturing',name:'製造與供應',items:[['production','建立量產與治具規範','包含關鍵製程、磁性驗收、ICT／FCT、校準及追溯。'],['supply','確認 BOM 與替代料','評估交期、生命週期、成本、替代料重驗與供應風險。']]},
  {id:'governance',name:'版本與維護',items:[['release','完成版本發行審查','凍結規格、BOM、PCB、韌體、報告；指定簽核責任人。'],['change','建立變更與現場回饋流程','定義 ECO、變更影響分析、重驗、客訴追蹤與資料保存。']]},
] as const;
export const sources = [
  {id:'S01',org:'Power Integrations',title:'RDR-1002 設計報告',version:'2024-04-26 · 114 頁',role:'完整設計報告的章節範本',url:'https://www.power.com/zh-hant/design-support/design-examples/rdr-1002-140-w-usb-pd-3pt1-epr-innoswitch5-pro-powigan-hiperpfs-5?language=zh-hant',note:'核對官方頁面與索引；未逐頁審核全文。'},
  {id:'S02',org:'Texas Instruments',title:'Power Stage Designer',version:'下載套件 01.00.00.0D · 手冊 Rev. B',role:'拓撲計算與互動工具架構',url:'https://www.ti.com/tool/POWERSTAGE-DESIGNER',note:'2023-02-23 套件日期；不代表所有文件的版本。'},
  {id:'S03',org:'Texas Instruments',title:'Power Supply Design Seminar',version:'各文件獨立版本',role:'PFC、LLC、EMI 與 Layout 技術資料',url:'https://www.ti.com/about-ti/events/power-supply-design-seminar/psds-library.html',note:'部分文件需登入。'},
  {id:'S04',org:'onsemi',title:'Switch-Mode Power Supply Reference Manual',version:'SMPSRM/D · Rev. 4 · 2014-04',role:'電源基礎與設計檢核參考',url:'https://www.onsemi.com/download/reference-manuals/pdf/smpsrm-d.pdf',note:'出版日期與搜尋引擎索引日期應分開看待。'},
  {id:'S05',org:'Infineon',title:'600 W LLC converter design guide',version:'V1.0 · 2021-11-11',role:'FHA 模型、設計假設與時域模擬比較',url:'https://www.infineon.com/assets/row/public/documents/24/42/infineon-design-guide-evaluation-board-eval-600w-12v-llc-p7-applicationnotes-en.pdf',note:'模型必須依實際電路與整流結構調整。'},
  {id:'S06',org:'NXP',title:'TEA2017 PFC + LLC 資源',version:'AN13140 Rev. 2.0 · 2025-08-04',role:'PFC＋LLC 控制與應用範例',url:'https://www.nxp.com/products/power-management/ac-dc-solutions/ac-dc-controllers-with-integrated-pfc/digital-configurable-llc-and-multimode-pfc-controller:TEA2017',note:'UM11613 Rev. 1.0；部分完整內容需登入。'},
  {id:'S07',org:'Analog Devices',title:'LTpowerCAD / LTpowerPlanner',version:'官方入口 · 未確認固定版號',role:'選型、Power Tree 與設計流程',url:'https://www.analog.com/en/lp/ltpowercad.html',note:'不同工具有各自適用的控制器與模型。'},
  {id:'S08',org:'Würth Elektronik',title:'REDEXPERT',version:'持續更新的線上工具',role:'元件損耗、電感與差模 EMI 濾波器',url:'https://www.we-online.com/en/support/design-tools/redexpert',note:'差模分析不能取代整機 EMC 驗證。'},
  {id:'S09',org:'TDK',title:'Ferrite Magnetic Design Tool',version:'官方入口 · 未確認固定版號',role:'磁材、氣隙與損耗分析',url:'https://www.tdk-electronics.tdk.com/en/180490/design-support/design-tools/ferrite-magnetic-design-tool',note:'必須確認材料、尺寸、溫度與波形適用性。'},
  {id:'S10',org:'Texas Instruments',title:'Semiconductor and IC Package Thermal Metrics',version:'SPRA953D · 2024-03',role:'正確使用熱阻與熱參數',url:'https://www.ti.com/lit/pdf/spra953',note:'封裝熱參數不能直接代替整機散熱模型。'},
  {id:'S11',org:'Nippon Chemi-Con',title:'鋁電解電容壽命技術說明',version:'官方技術說明',role:'溫度、漣波與壽命估算邊界',url:'https://www.chemi-con.co.jp/en/faq/detail.php?id=alLifetime',note:'各系列的係數與使用範圍需個別核對。'},
  {id:'S12',org:'IEC',title:'IEC 62368-1',version:'2023 · Ed. 4',role:'影音、資訊與通訊設備安全範圍',url:'https://webstore.iec.ch/en/publication/69308',note:'官方版本資訊；本工具未內建付費標準全文或認證判定。'},
  {id:'S13',org:'IEC',title:'IEC 61347-1',version:'2024 · Ed. 4',role:'光源控制裝置安全範圍',url:'https://webstore.iec.ch/en/publication/64758',note:'應依產品分類選擇適用標準。'},
  {id:'S14',org:'IEC / CISPR',title:'CISPR 32',version:'2015 + AMD1:2019',role:'多媒體設備發射要求',url:'https://webstore.iec.ch/en/publication/65836',note:'需依市場及產品類別確認採用版本。'},
  {id:'S15',org:'IEC',title:'IEC 61000-3-2',version:'2018 + AMD1:2020 + AMD2:2024',role:'輸入諧波電流限制',url:'https://webstore.iec.ch/en/publication/92799',note:'適用範圍與類別需確認；不可只憑 PF 判定合規。'},
  {id:'S16',org:'IEC',title:'IEC 61000-4-5',version:'2014 + AMD1:2017',role:'突波抗擾度測試方法',url:'https://webstore.iec.ch/en/publication/61166',note:'測試等級由適用產品要求決定。'},
  {id:'S17',org:'IECEE',title:'TRF cispr 32,35D:2025',version:'2025 · Ed. 5',role:'測試報告格式參考',url:'https://webstore.iec.ch/en/publication/107567',note:'付費格式，未閱覽全文或在此重製。'},
  {id:'S18',org:'USB-IF',title:'USB Power Delivery',version:'官方規格與合規入口',role:'USB PD 產品擴充參考',url:'https://www.usb.org/usb-charger-pd',note:'提供單埠電壓／電流／功率上限檢查；不含協定模擬或合規判定。'},
  {id:'S19',org:'NXP',title:'TEA2209T 主動橋控制器',version:'Rev.1.1 · 2021-04-14',role:'四 MOSFET AC 主動整流，含 COMP 停用控制',url:'https://www.nxp.com/docs/en/data-sheet/TEA2209T.pdf',note:'第 8.2 節：COMP_POL 固定接 GND 或 VCC；依極性確認停用訊號。'},
  {id:'S20',org:'Renesas',title:'RRW11011 PFC + HWLLC',version:'公開簡版 Rev.0.01 · 2026-03-03',role:'交錯 Boost PFC、HWLLC 與自適應母線架構',url:'https://www.renesas.com/en/document/sds/rrw11011-short-form-datasheet',note:'R16DO0072EU0001。簡版不能取代完整資料表、控制器選項表與實機電路圖。'},
  {id:'S21',org:'Renesas',title:'RRW40120 半橋驅動器',version:'Rev.0.04 · 2026-03-04',role:'高／低側閘極驅動、UVLO 與互鎖',url:'https://www.renesas.com/en/document/dst/rrw40120-datasheet',note:'第 6 頁建議：VCC、VB−VS 為 10～18 V；VS 上限 600 V。'},
  {id:'S22',org:'Renesas',title:'RRW43110 SR 控制器',version:'Rev.0.03 · 2026-03-05',role:'HWLLC 半波次級同步整流',url:'https://www.renesas.com/en/document/dst/rrw43110-datasheet',note:'支援至 300 kHz；第 6 頁 VD 建議上限 135 V，絕對最大值 145 V。'},
  {id:'S23',org:'Renesas',title:'RRW30120 PD／次級控制器',version:'Rev.01.00 · 2026-03-04',role:'USB PD EPR、次級調節、光耦回授與 VBUS 控制',url:'https://www.renesas.com/en/document/dst/rrw30120-datasheet',note:'EPR 至 48 V。單埠 240 W 上限與整機總功率應分開設計；需核對韌體與 PDO。'},
];
export const limitations = 'HWLLC 模式提供能量預算與控制器範圍檢查；增益、諧振及 ZVS 模型尚未建立。一般 LLC 模式的 FHA 僅適用半橋、中心抽頭全波整流，Ns 指半個次級繞組。未計寄生、非線性磁性、閉迴路與動態效應。解析符合不代表安規或量產放行。';
