export const domains = [
  {id:'requirements', name:'需求與任務', items:[['mission','建立產品任務與使用情境','定義負載輪廓、使用時數、海拔、環境與預期壽命。'],['markets','確認市場與合規範圍','依產品分類、銷售國家與版本制定合規矩陣。']]},
  {id:'specifications',name:'電氣規格',items:[['limits','建立完整輸入／輸出容差','包含線路、負載、漣波、過衝、待機及動態條件。'],['hold-real','量測保持時間與掉電行為','最低輸入、滿載與最低電容量下，量測輸出及控制供電。']]},
  {id:'architecture',name:'架構與效率',items:[['topology','完成拓撲與成本取捨','比較效率、功率密度、控制難度、隔離需求與 BOM。'],['eff-real','建立全範圍效率地圖','量測高低線、輕重載、待機及儀器誤差；核對損耗分布。']]},
  {id:'input',name:'輸入與 PFC',items:[['inrush','驗證突入與重啟','確認保險絲、NTC／繼電器、整流器與熱重啟。'],['pf-thd','量測 PF 與諧波','依適用產品類別、負載與標準測試；PF 假設不能取代測試。']]},
  {id:'powerstage',name:'功率級與 LLC',items:[['zvs','驗證 ZVS 與換流餘裕','涵蓋容差、輸入與負載；量測死區內 Vds、電流與磁化電流。'],['stress','確認峰值與 RMS 應力','包含啟動、短路、突卸載、寄生振鈴與電容 RMS。']]},
  {id:'magnetics',name:'磁性元件',items:[['core','確認磁芯損耗與飽和','記錄材料、Ae、氣隙、ΔB、偏磁、頻率、溫度及批次容差。'],['winding','確認繞組損耗與絕緣','記錄線徑、層次、漏感、集膚／鄰近效應與繞製圖。']]},
  {id:'components',name:'元件與降額',items:[['derating','建立元件應力降額表','逐顆核對電壓、電流、功率、溫度與資料表條件。'],['capacitors','核對電容漣波與壽命','依原廠係數評估熱點、頻率與漣波；不得套用通用壽命公式。']]},
  {id:'control',name:'控制與韌體',items:[['loop','驗證迴路與瞬態','提供 Bode、負載階躍、線路暫態、啟動及突卸載資料。'],['firmware','記錄控制器與韌體版本','含頻率限幅、死區、軟啟動、brownout、參數 CRC 與回復流程。']]},
  {id:'thermal',name:'熱與機構',items:[['thermal-map','建立最差條件溫度圖','涵蓋外殼、半導體、磁性與電容；記錄風速、安裝方式與環境。'],['junction','驗證接面與熱介面','使用適當熱模型與量測方法；不可直接以封裝 θJA 推導所有機構。']]},
  {id:'emc',name:'PCB 與 EMC',items:[['layout','檢視高 di/dt 與 dv/dt 回路','確認功率迴路、回流、閘極、Kelvin、感測、Y 電容與接地。'],['emi','完成傳導／輻射預掃','保留配置、線材、LISN、接地、負載及與限值間的餘裕。']]},
  {id:'safety',name:'安規與隔離',items:[['insulation','建立絕緣與距離表','依產品標準、工作電壓、污染度、材料群組、海拔及隔離類型確認。'],['safety-tests','完成適用安規測試','依合規矩陣執行耐壓、接觸電流、接地、異常及溫升測試。']]},
  {id:'protection',name:'保護與 FMEA',items:[['protection-tests','驗證所有保護與復歸','包含 OVP、OCP、SCP、OTP、UVLO、感測開短路與重複動作。'],['fmea','完成故障模式分析','評估單點故障、嚴重度、可偵測性、措施與殘餘風險。']]},
  {id:'reliability',name:'可靠度與壽命',items:[['life','確認壽命任務條件','依負載／溫度任務分布，計算並驗證限制元件壽命。'],['environment','驗證環境與機械應力','按用途規劃溫循、濕熱、振動、跌落及包裝測試。']]},
  {id:'validation',name:'量測與驗證',items:[['instrument','確認儀器與量測不確定度','記錄校驗、頻寬、探棒、接線、共模能力與誤差。'],['dvp','完成設計驗證矩陣','每項規格需對應方法、樣本數、條件、結果、責任人与報告版本。']]},
  {id:'manufacturing',name:'製造與供應',items:[['production','建立量產與治具規範','包含關鍵製程、磁性驗收、ICT／FCT、校準及追溯。'],['supply','確認 BOM 與替代料','評估交期、生命週期、成本、替代料重驗與供應風險。']]},
  {id:'governance',name:'版本與維護',items:[['release','完成版本發行審查','凍結規格、BOM、PCB、韌體、報告；指定簽核責任人。'],['change','建立變更與現場回饋流程','定義 ECO、變更影響分析、重驗、客訴追蹤與資料保存。']]},
] as const;
export const sources = [
  {id:'S01',org:'Power Integrations',title:'RDR-1002 設計報告',version:'2024-04-26 · 114 頁',role:'完整設計報告的章節範本',url:'https://www.power.com/zh-hant/design-support/design-examples/rdr-1002-140-w-usb-pd-3pt1-epr-innoswitch5-pro-powigan-hiperpfs-5?language=zh-hant',note:'核對官方頁面與索引；未逐頁審核全文。'},
  {id:'S02',org:'Texas Instruments',title:'Power Stage Designer',version:'下載套件 01.00.00.0D · 手冊 Rev. B',role:'拓撲計算與互動工具架構',url:'https://www.ti.com/tool/POWERSTAGE-DESIGNER',note:'2023-02-23 套件日期；不代表所有文件的版本。'},
  {id:'S03',org:'Texas Instruments',title:'Power Supply Design Seminar',version:'各文件獨立版本',role:'PFC、LLC、EMI 與 Layout 技術資料',url:'https://www.ti.com/about-ti/events/power-supply-design-seminar/psds-library.html',note:'部分文件需登入。'},
  {id:'S04',org:'onsemi',title:'Switch-Mode Power Supply Reference Manual',version:'SMPSRM/D · Rev. 4 · 2014-04',role:'電源基礎與設計檢核參考',url:'https://www.onsemi.com/download/reference-manuals/pdf/smpsrm-d.pdf',note:'出版日期與搜尋引擎索引日期應分開看待。'},
  {id:'S05',org:'Infineon',title:'600 W LLC converter design guide',version:'V1.0 · 2021-11-11',role:'FHA 模型、設計假設與時域模擬比較',url:'https://www.infineon.com/assets/row/public/documents/24/42/infineon-design-guide-evaluation-board-eval-600w-12v-llc-p7-applicationnotes-en.pdf',note:'模型必須依實際電路與整流結構調整。'},
  {id:'S06',org:'NXP',title:'TEA2017 PFC + LLC 資源',version:'AN13140 Rev. 2.0 · 2025-08-04',role:'PFC＋LLC 控制與應用範例',url:'https://www.nxp.com/products/power-management/ac-dc-solutions/ac-dc-controllers-with-integrated-pfc/digital-configurable-llc-and-multimode-pfc-controller:TEA2017',note:'UM11613 Rev. 1.0；部分完整內容需登入。'},
  {id:'S07',org:'Analog Devices',title:'LTpowerCAD / LTpowerPlanner',version:'官方入口 · 未確認固定版號',role:'選型、Power Tree 與設計流程',url:'https://www.analog.com/en/lp/ltpowercad.html',note:'不同工具有各自適用的控制器與模型。'},
  {id:'S08',org:'Würth Elektronik',title:'REDEXPERT',version:'持續更新的線上工具',role:'元件損耗、電感與差模 EMI 濾波器',url:'https://www.we-online.com/en/support/design-tools/redexpert',note:'差模分析不能取代整機 EMC 驗證。'},
  {id:'S09',org:'TDK',title:'Ferrite Magnetic Design Tool',version:'官方入口 · 未確認固定版號',role:'磁材、氣隙與損耗分析',url:'https://www.tdk-electronics.tdk.com/en/180490/design-support/design-tools/ferrite-magnetic-design-tool',note:'必須確認材料、尺寸、溫度與波形適用性。'},
  {id:'S10',org:'Texas Instruments',title:'Semiconductor and IC Package Thermal Metrics',version:'SPRA953D · 2024-03',role:'正確使用熱阻與熱參數',url:'https://www.ti.com/lit/pdf/spra953',note:'封裝熱參數不能直接代替整機散熱模型。'},
  {id:'S11',org:'Nippon Chemi-Con',title:'鋁電解電容壽命技術說明',version:'官方技術說明',role:'溫度、漣波與壽命估算邊界',url:'https://www.chemi-con.co.jp/en/faq/detail.php?id=alLifetime',note:'各系列的係數與使用範圍需個別核對。'},
  {id:'S12',org:'IEC',title:'IEC 62368-1',version:'2023 · Ed. 4',role:'影音、資訊與通訊設備安全範圍',url:'https://webstore.iec.ch/en/publication/69308',note:'官方版本資訊；本工具未內建付費標準全文或認證判定。'},
  {id:'S13',org:'IEC',title:'IEC 61347-1',version:'2024 · Ed. 4',role:'光源控制裝置安全範圍',url:'https://webstore.iec.ch/en/publication/64758',note:'應依產品分類選擇適用標準。'},
  {id:'S14',org:'IEC / CISPR',title:'CISPR 32',version:'2015 + AMD1:2019',role:'多媒體設備發射要求',url:'https://webstore.iec.ch/en/publication/65836',note:'需依市場及產品類別確認採用版本。'},
  {id:'S15',org:'IEC',title:'IEC 61000-3-2',version:'2018 + AMD1:2020 + AMD2:2024',role:'輸入諧波電流限制',url:'https://webstore.iec.ch/en/publication/92799',note:'適用範圍與類別需確認；不可只憑 PF 判定合規。'},
  {id:'S16',org:'IEC',title:'IEC 61000-4-5',version:'2014 + AMD1:2017',role:'突波抗擾度測試方法',url:'https://webstore.iec.ch/en/publication/61166',note:'測試等級由適用產品要求決定。'},
  {id:'S17',org:'IECEE',title:'TRF cispr 32,35D:2025',version:'2025 · Ed. 5',role:'測試報告格式參考',url:'https://webstore.iec.ch/en/publication/107567',note:'付費格式，未閱覽全文或在此重製。'},
  {id:'S18',org:'USB-IF',title:'USB Power Delivery',version:'官方規格與合規入口',role:'USB PD 產品擴充參考',url:'https://www.usb.org/usb-charger-pd',note:'本版尚未提供 USB PD 協定設計或合規檢核。'},
];
export const limitations = '本版為半橋 LLC、中心抽頭全波整流的 FHA 與能量預算模型；Ns 指半個次級繞組。未計寄生、整流壓降、非線性磁性、閉迴路、突波與動態效應。曲線不判定 ZVS，解析檢核不代表安規或量產放行。';
