import { domains, limitations, sources } from './catalog.ts';
import { reviewStatus } from './review.ts';
import {fingerprint,type Project,type Result} from './model.ts';
const escape = (s: unknown) => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function reportHtml(project: Project, result: Result) {
  const rows = Object.entries(result.metrics).map(([k,v]) => `<tr><td>${escape(k)}</td><td>${v===null?escape(k==='caseC'?'未提供有效熱阻':k==='bridgeConductionW'?(project.spec.rectifier==='diode'?'不適用：二極體橋':'未提供熱態 RDS(on)'):k==='boostDuty'?'不符合 Boost 工作點條件':k.startsWith('hw')?(project.spec.topology!=='hwllc'?'不適用：一般 LLC':k==='hwOnHalfRatio'?'未提供導通時間或有效 LC 估算':'未確認接法或缺少 LC 參數'):'HWLLC：模型待建立'):escape(v.toFixed(4))}</td></tr>`).join('');
  const checks = result.checks.map(c=>`<tr><td>${escape(c.title)}</td><td>${escape(c.status)}</td><td>${escape(c.detail)}</td></tr>`).join('');
  const evidence = domains.map(d=>`<h3>${escape(d.name)}</h3><table>${d.items.map(([id,title])=>`<tr><td>${escape(title)}</td><td>${escape(reviewStatus(project,id))}</td><td>${escape(project.evidence[id]?.note??'尚未提供證據')}<br>${escape(project.evidence[id]?.method??'')} ${escape(project.evidence[id]?.updatedAt??'')}</td></tr>`).join('')}</table>`).join('');
  return `<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><title>${escape(project.name)} — 設計報告</title><style>body{font:15px/1.7 system-ui,sans-serif;color:#172339;max-width:960px;margin:36px auto;padding:0 24px}h1,h2{letter-spacing:-.02em}table{border-collapse:collapse;width:100%;margin:16px 0;table-layout:fixed}td,th{border:1px solid #d7dfe8;padding:8px;overflow-wrap:anywhere;text-align:left}td:first-child{width:32%}small{color:#57677c}.note{background:#eff4fa;padding:16px}pre{white-space:pre-wrap;overflow-wrap:anywhere}@media print{body{margin:0}tr{break-inside:avoid}h2,h3{break-after:avoid}}</style><h1>${escape(project.name)}</h1><p>Power Design 360 · 引擎 ${escape(result.version)} · ${escape(new Date().toISOString())}</p><p>${escape(project.description)}</p><p class="note">${escape(limitations)}<br>使用者填寫的證據未經第三方查核。本報告不是認證或簽核。</p>${project.design?`<h2>自動設計起點</h2><p>${project.design.specKey===fingerprint(project.spec)?'對應目前規格；仍需硬體驗證':'規格已修改：以下為產生當時的歷史方案，須重新設計'}</p><pre>${escape(project.design.summary)}</pre><h3>原始需求</h3><pre>${escape(JSON.stringify(project.design.requirements,null,2))}</pre>`:''}<h2>解析檢核</h2><table>${checks}</table><h2>計算值（欄位名稱含單位）</h2><table>${rows}</table><p>efficiency 為 %；ratio、k、q、gainTarget、gainHold、boostDuty、hwCapRatio、hwOnHalfRatio 無單位；rac 為 Ω。</p><h2>控制器參考版本</h2><table>${sources.filter(s=>['S18','S19','S20','S21','S22','S23'].includes(s.id)).map(s=>`<tr><td>${escape(s.title)}</td><td>${escape(s.version)}<br><a href="${escape(s.url)}">官方文件</a></td></tr>`).join('')}</table><h2>輸入規格</h2><pre>${escape(JSON.stringify(project.spec,null,2))}</pre><h2>工程審查與證據</h2>${evidence}<p><small>原始參數與證據請另外匯出專案 JSON 保存。</small></p></html>`;
}
export function downloadText(name: string, text: string, type: string) {
  const url = URL.createObjectURL(new Blob([text],{type}));
  const a = document.createElement('a'); a.href=url; a.download=name; a.click();
  setTimeout(()=>URL.revokeObjectURL(url),1000);
}
