import {useState} from 'react';
import {Activity,LoaderCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import type {Project,Result} from '@/lib/power/model';
import {requestCalculation} from './client-api';
import {fmt} from './dashboard';
export function Comparison({projects,apiBase}:{projects:Project[];apiBase:string}){
 const [ids,setIds]=useState<string[]>(projects.slice(0,3).map(p=>p.id)),[results,setResults]=useState<Record<string,Result>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const chosen=projects.filter(p=>ids.includes(p.id));
 async function compare(){setBusy(true);setError('');setResults({});try{const r=await Promise.all(chosen.map(async p=>[p.id,await requestCalculation(p.spec,apiBase)] as const));setResults(Object.fromEntries(r));}catch(e){setError(e instanceof Error?e.message:'計算服務無法使用。');}finally{setBusy(false);}}
 const rows:{label:string;key:keyof Result['metrics'];unit:string}[]=[{label:'輸出功率',key:'outputW',unit:'W'},{label:'整機效率預算',key:'efficiency',unit:'%'},{label:'總損耗預算',key:'totalLossW',unit:'W'},{label:'低線輸入電流',key:'inputLowA',unit:'A'},{label:'諧振頻率',key:'frKhz',unit:'kHz'},{label:'有效保持時間',key:'holdMs',unit:'ms'},{label:'需求有效電容量',key:'requiredCapUf',unit:'µF'},{label:'滿載 Q',key:'q',unit:''},{label:'額定需求增益',key:'gainTarget',unit:''},{label:'保持終點需求增益',key:'gainHold',unit:''},{label:'機殼集總溫度',key:'caseC',unit:'°C'}];
 return <><div className="section-intro"><h2>不同參數，同一個比較基準。</h2><p>勾選最多三個已建立的專案，以相同版本的後端模型重新計算。</p></div><div className="compare-selector">{projects.map(p=><label key={p.id} className={ids.includes(p.id)?'selected':''}><input type="checkbox" checked={ids.includes(p.id)} disabled={busy||(!ids.includes(p.id)&&ids.length>=3)} onChange={e=>{setIds(e.target.checked?[...ids,p.id]:ids.filter(id=>id!==p.id));setResults({});}}/><div><strong>{p.name}</strong><span>{p.spec.outputV*p.spec.outputA} W · {p.spec.lrUh} µH / {p.spec.crNf} nF</span></div></label>)}</div>{projects.length<2&&<p className="note-box">目前只有一案。使用上方「複製」建立不同參數的方案，即可並排比較。</p>}<Button onClick={compare} disabled={busy||!chosen.length}>{busy?<LoaderCircle className="animate-spin" size={16}/>:<Activity size={16}/>}計算選取方案</Button>{error&&<p role="alert" className="error-banner">{error}</p>}<section className="panel comparison-table"><Table><TableHeader><TableRow><TableHead>比較項目</TableHead>{chosen.map(p=><TableHead key={p.id}>{p.name}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r.key}><TableCell>{r.label} <small>{r.unit}</small></TableCell>{chosen.map(p=><TableCell className="mono" key={p.id}>{fmt(results[p.id]?.metrics[r.key])}</TableCell>)}</TableRow>)}</TableBody></Table></section><p className="muted">效率為預算；溫度空白代表未提供有效熱阻。此表不會自動選出可量產的最佳方案。</p></>;
}
