'use client';
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ReferenceLine, Legend } from 'recharts';
import { ArrowRight, ArrowUpRight, Check, Circle, CircleAlert, Clock3, Cpu, Gauge, Waves, Zap } from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { Project, Result } from '@/lib/power/model';
import { Platform } from './platform';
import { reviewCounts } from '@/lib/power/review';
export const fmt = (n:number|null|undefined,d=2) => n===null||n===undefined?'—':n.toLocaleString('en-US',{maximumFractionDigits:d,minimumFractionDigits:d});
export function Status({status,auto=false}:{status:string;auto?:boolean}) {
 const label:Record<string,string> = {pass:auto?'解析符合':'已附證據',fail:'需處理',pending:'待驗證',stale:'需重審',na:'不適用'};
 const Icon = status==='pass'?Check:status==='fail'?CircleAlert:status==='stale'?Clock3:Circle;
 return <span className={`status status-${status}`}><Icon size={13}/>{label[status]??status}</span>;
}
export function Dashboard({project,result,onTab}:{project:Project;result:Result|null;onTab:(s:string)=>void}) {
 const m=result?.metrics,c=reviewCounts(project),hw=project.spec.topology==='hwllc';
 return <>
 <div className="metric-grid">{[
  {title:'額定輸出功率',value:fmt(m?.outputW,0),unit:'W',sub:`${project.spec.outputV} V × ${project.spec.outputA} A`,icon:Zap,tone:'indigo'},
  {title:'整機效率預算',value:fmt(m?.efficiency),unit:'%',sub:`設計目標 ≥ ${project.spec.targetEfficiency}%`,icon:Gauge,tone:'teal'},
  hw?{title:'電容能量可供時間',value:fmt(m?.holdMs,1),unit:'ms',sub:'調節能力仍需驗證',icon:Waves,tone:'blue'}:{title:'LLC 諧振頻率',value:fmt(m?.frKhz,1),unit:'kHz',sub:'Lr 與 Cr 解析結果',icon:Waves,tone:'blue'},
  {title:'總損耗預算',value:fmt(m?.totalLossW,1),unit:'W',sub:'依輸入的級間效率估計',icon:Cpu,tone:'orange'},
 ].map(item=><section className="metric-card" key={item.title}><div className="metric-top"><span>{item.title}</span><item.icon size={19} className={`tone-${item.tone}`}/></div><div className="metric-value">{item.value}<small>{item.unit}</small></div><p>{item.sub}</p></section>)}</div>
 <div className="dashboard-grid">{hw?<Platform spec={project.spec}/>:<section className="panel chart-panel"><div className="panel-heading spread"><div><div className="eyebrow">RESONANT TANK</div><h2>LLC 增益特性</h2><p>負載變化下的 FHA 解析曲線</p></div><span className="subtle-chip">半橋 LLC</span></div>
 {result?<><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><LineChart data={result.curves} margin={{top:14,right:20,left:0,bottom:10}}><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#e5eaf2"/><XAxis dataKey="frequency" type="number" domain={['dataMin','dataMax']} tickFormatter={v=>String(Math.round(v))} tickLine={false} axisLine={false} tick={{fill:'#708099',fontSize:12}} label={{value:'開關頻率 (kHz)',position:'insideBottom',offset:-8,fill:'#708099',fontSize:12}}/><YAxis tickLine={false} axisLine={false} tickFormatter={v=>fmt(v,1)} tick={{fill:'#708099',fontSize:12}} width={43} domain={[0,'auto']}/><Tooltip contentStyle={{border:'1px solid #e5eaf2',borderRadius:10,fontSize:13}} labelFormatter={v=>`${fmt(Number(v),1)} kHz`} formatter={(v)=>fmt(Number(v),3)}/><ReferenceLine x={result.metrics.frKhz??undefined} stroke="#9ba8bd" strokeDasharray="4 4" label={{value:'fr',position:'top',fill:'#7b8798',fontSize:12}}/><ReferenceLine y={result.metrics.gainTarget??undefined} stroke="#f1a43c" strokeDasharray="5 4"/><Line name="10% 負載" dataKey="low" stroke="#a4b0f4" dot={false} strokeWidth={2} isAnimationActive={false}/><Line name="50% 負載" dataKey="half" stroke="#6996cd" dot={false} strokeWidth={2} isAnimationActive={false}/><Line name="100% 負載" dataKey="full" stroke="#5754d9" dot={false} strokeWidth={2.5} isAnimationActive={false}/><Legend iconType="plainline" wrapperStyle={{fontSize:12,paddingTop:18}}/></LineChart></ResponsiveContainer></div><div className="chart-meta"><span>k <b>{fmt(m?.k,1)}</b></span><span>Q 滿載 <b>{fmt(m?.q,3)}</b></span><span>額定需求增益 <b className="text-amber">{fmt(m?.gainTarget,3)}</b></span></div></>:<div className="empty-chart"><Waves size={32}/><p>執行計算以更新曲線</p></div>}
 <p className="panel-footnote">虛線為額定需求增益。曲線不代表 ZVS 或閉迴路穩定性。</p></section>}
 <section className="panel checks-panel"><div className="panel-heading spread"><div><div className="eyebrow">DESIGN CHECK</div><h2>解析檢核</h2></div><span className="count-label">{result?.checks.filter(c=>c.status==='pass').length??0} / {result?.checks.length??0} 符合</span></div><div className="auto-checks">{result?result.checks.map(c=><div className="auto-check" key={c.id}><div><Status status={c.status} auto/><h3>{c.title}</h3></div><p>{c.detail}</p></div>):<p className="muted empty-hint">尚無目前規格的計算結果。</p>}</div><Button variant="ghost" className="panel-link" onClick={()=>onTab('spec')}>調整設計參數 <ArrowRight size={16}/></Button></section></div>
 <div className="dashboard-bottom"><section className="panel"><div className="panel-heading spread"><div><div className="eyebrow">POWER BUDGET</div><h2>功率與損耗分配</h2></div><span className="subtle-chip">效率假設</span></div><div className="power-flow"><div><span>AC 輸入</span><strong>{fmt(m?.inputW,1)} <small>W</small></strong><small>{fmt(m?.inputLowA,2)} A @ {project.spec.vacMin} VAC</small></div><ArrowRight/><div><span>PFC 母線</span><strong>{fmt(m?.busW,1)} <small>W</small></strong><small>整流＋PFC {fmt(m?.pfcLossW,1)} W</small></div><ArrowRight/><div><span>DC 輸出</span><strong>{fmt(m?.outputW,0)} <small>W</small></strong><small>DC/DC 損耗 {fmt(m?.dcLossW,1)} W</small></div></div>{project.spec.rectifier==='tea2209'&&<p className="panel-footnote">主動橋低線導通：{fmt(m?.bridgeConductionW)} W（含於前級預算；未填熱態 RDS(on) 時不估算）。</p>}</section>
 <section className="panel review-summary"><div><div className="eyebrow">ENGINEERING REVIEW</div><h2>360° 設計審查</h2><p>16 個面向 · {c.total} 項工程檢核</p></div><div className="review-score"><strong>{c.pass+c.na}<span> / {c.total}</span></strong><span>已記錄且版本有效</span></div><div className="progress-track"><div style={{width:`${(c.pass+c.na)/c.total*100}%`}}/></div><Button variant="ghost" className="panel-link" onClick={()=>onTab('review')}>建立驗證證據 <ArrowUpRight size={16}/></Button></section></div>
 </>;
}
