import {useState} from 'react';
import {ArrowRight, ExternalLink, Code2, Search} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {sources,limitations} from '@/lib/power/catalog';
import {ENGINE_VERSION} from '@/lib/power/model';
export const GITHUB='https://github.com/alger68/alger68.github.io/tree/main/power-design-360/source';
export function Sources(){
 const [q,setQ]=useState('');const list=sources.filter(s=>`${s.org} ${s.title} ${s.role}`.toLowerCase().includes(q.toLowerCase()));
 return <><div className="section-intro"><h2>設計有依據，版本可追溯。</h2><p>18 項原廠與標準組織資源，作為規範與工具的參考起點。下列為查核版本，未宣稱全部為最新版本。</p></div><div className="list-toolbar"><div className="search-input"><Search size={17}/><Input aria-label="搜尋原廠資料" placeholder="搜尋原廠、工具或設計主題…" value={q} onChange={e=>setQ(e.target.value)}/></div><span className="muted">{list.length} 項資源 · 查核 2026-09-23</span></div><div className="sources-grid">{list.map(s=><a href={s.url} target="_blank" rel="noreferrer" className="panel source-card" key={s.id}><div className="source-top"><span>{s.org}</span><ExternalLink size={17}/></div><h2>{s.title}</h2><p className="source-role">{s.role}</p><div className="source-version">{s.version}</div><p className="source-note">{s.note}</p><span className="source-id">{s.id} <ArrowRight size={16}/></span></a>)}</div>{!list.length&&<div className="panel empty-hint">沒有符合的資料，試試 LLC、TI 或熱設計。</div>}</>;
}
export function Guide(){return <div className="guide-grid"><section className="panel prose-panel"><div className="eyebrow">GETTING STARTED</div><h2>從規格，到一份可以審查的報告</h2><ol><li><strong>建立專案</strong><p>示範預設為 480 W / 48 V；請改為你的設計規格。每個瀏覽器有自己的專案。</p></li><li><strong>輸入參數並執行計算</strong><p>由後端檢查輸入範圍，產生功率預算、保持時間與 LLC FHA 曲線。效率與 PF 由你提供。</p></li><li><strong>完成 16 面向檢核</strong><p>記錄實測、模擬或文件證據。未填資料與待重審項目，不會被視為通過。</p></li><li><strong>比較與匯出</strong><p>複製專案建立不同方案；最多同時比較三案。匯出 JSON 保留可編輯資料，HTML 報告可在瀏覽器列印為 PDF。</p></li></ol></section><section className="panel prose-panel"><div className="eyebrow">MODEL BOUNDARIES</div><h2>理解模型的適用範圍</h2><p>{limitations}</p><dl><dt>功率預算</dt><dd>ηtotal = ηPFC × ηLLC；輸入功率 = Pout / ηtotal。損耗來自效率假設，尚無逐元件損耗模型。</dd><dt>保持時間</dt><dd>t = Ceff × (Vbus² − Vend²) / (2 × Pbus)。未含 ESR、老化與額外控制損耗；需另外驗證低母線調節能力。</dd><dt>LLC FHA</dt><dd>fr = 1 / (2π√LrCr)；k = Lm/Lr；Rac = 8n²Rload/π²；Q = √(Lr/Cr)/Rac；Fn = fs/fr。</dd><dt>增益</dt><dd>M = 1 / √((1 + (1 − 1/Fn²)/k)² + Q²(Fn − 1/Fn)²)。需求 M = 2nVo/Vbus；n = Np/Ns，Ns 是次級半繞組。</dd><dt>機殼溫度</dt><dd>Tcase = Tamb + Ploss × Rθeffective。熱阻需對應實際機構；不能推算元件接面溫度。</dd></dl></section><section className="panel prose-panel"><div className="eyebrow">YOUR DATA</div><h2>儲存與分享方式</h2><p>專案自動保存在此瀏覽器，最多 30 案。清除網站資料、更換裝置或使用另一個網站入口，都不會帶入原本專案，請定期匯出 JSON。</p><p>執行計算會將數值參數傳送到本工具後端；API 不建立專案資料庫，不接收專案名稱與證據文字。平台仍可能保存一般請求日誌。</p><p>本版沒有帳號、雲端同步、多人共同編輯、SPICE、器件自動選型或認證簽核。可由 GitHub 原始碼延伸。</p></section><section className="panel prose-panel"><div className="eyebrow">VERSION & GOVERNANCE</div><h2>持續擴充的工程規範</h2><p>引擎版本 {ENGINE_VERSION}。檢核表是本工具的原創工程框架；原廠文件與標準保留各自權利，本工具提供官方連結。</p><p>公開版無需登入。各公司可自行部署，替換檢核條文、元件模型與後端儲存機制。正式審查需由有權責的人員完成。</p><Button variant="outline" asChild><a href={GITHUB} target="_blank" rel="noreferrer"><Code2 size={16}/>查看原始碼與部署說明</a></Button></section></div>;}
