import { useState } from 'react';
import { FileCheck2, Search } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter } from '@/components/ui/dialog';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { domains } from '@/lib/power/catalog';
import { fingerprint,specSchema,type Project,type Evidence } from '@/lib/power/model';
import { reviewCounts,reviewStatus } from '@/lib/power/review';
import { Status } from './dashboard';
export function Reviews({project,onEvidence}:{project:Project;onEvidence:(id:string,e:Evidence)=>void}) {
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('all');
 const [edit,setEdit]=useState<{id:string;title:string;hint:string}|null>(null),[note,setNote]=useState(''),[verdict,setVerdict]=useState<Evidence['verdict']>('pass'),[method,setMethod]=useState<Evidence['method']>('measurement');
 const c=reviewCounts(project), valid=specSchema.safeParse(project.spec).success;
 function open(id:string,title:string,hint:string) {const e=project.evidence[id];setEdit({id,title,hint});setNote(e?.note??'');setVerdict(e?.verdict??'pass');setMethod(e?.method??'measurement');}
 return <><div className="review-banner"><FileCheck2 size={26}/><div><h2>讓每一項設計決策，都有依據</h2><p>依序補齊 16 個面向。填寫報告編號、測試條件及結果；由你確認判定。</p></div><span>{c.pass+c.na}<small> / {c.total} 已記錄</small></span></div><div className="list-toolbar"><div className="search-input"><Search size={17}/><Input aria-label="搜尋檢核項目" placeholder="搜尋檢核項目、面向…" value={query} onChange={e=>setQuery(e.target.value)}/></div><Select value={filter} onValueChange={setFilter}><SelectTrigger aria-label="篩選檢核狀態" className="filter-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">所有狀態</SelectItem><SelectItem value="pending">待驗證 / 需重審</SelectItem><SelectItem value="pass">已附證據</SelectItem><SelectItem value="fail">需處理</SelectItem><SelectItem value="na">不適用</SelectItem></SelectContent></Select></div>
 <div className="review-list">{domains.map((d,index)=>{const items=d.items.filter(([id,title,hint])=>{const st=reviewStatus(project,id);return `${d.name}${title}${hint}`.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||(filter==='pending'?(st==='pending'||st==='stale'):st===filter));});return items.length?<section className="panel domain-panel" key={d.id}><div className="domain-heading"><span>{String(index+1).padStart(2,'0')}</span><h2>{d.name}</h2></div>{items.map(([id,title,hint])=><div className="review-row" key={id}><div><h3>{title}</h3><p>{hint}</p>{project.evidence[id]&&<div className="evidence-preview">證據：{project.evidence[id].note}</div>}</div><Status status={reviewStatus(project,id)}/><Button variant="outline" size="sm" onClick={()=>open(id,title,hint)} disabled={!valid}>{project.evidence[id]?'檢視 / 更新':'新增證據'}</Button></div>)}</section>:null;})}</div>
 {!domains.some(d=>d.items.some(([id,title,hint])=>`${d.name}${title}${hint}`.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||(filter==='pending'?['pending','stale'].includes(reviewStatus(project,id)):reviewStatus(project,id)===filter))))&&<div className="panel empty-hint">找不到符合條件的項目，請調整搜尋或篩選。</div>}
 <Dialog open={!!edit} onOpenChange={v=>!v&&setEdit(null)}><DialogContent className="evidence-dialog"><DialogHeader><DialogTitle>{edit?.title}</DialogTitle><DialogDescription>{edit?.hint}</DialogDescription></DialogHeader><div className="field-grid"><div className="field"><label>審查判定</label><Select value={verdict} onValueChange={v=>setVerdict(v as Evidence['verdict'])}><SelectTrigger aria-label="審查判定"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="pass">符合要求</SelectItem><SelectItem value="fail">需改善 / 不符合</SelectItem><SelectItem value="na">不適用（需理由）</SelectItem></SelectContent></Select></div><div className="field"><label>證據類型</label><Select value={method} onValueChange={v=>setMethod(v as Evidence['method'])}><SelectTrigger aria-label="證據類型"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="measurement">實測記錄</SelectItem><SelectItem value="simulation">模擬分析</SelectItem><SelectItem value="review">文件審查</SelectItem></SelectContent></Select></div></div><div className="field"><label htmlFor="evidence-note">條件、結果與報告編號</label><Textarea id="evidence-note" rows={6} value={note} maxLength={4000} onChange={e=>setNote(e.target.value)} placeholder="例如：EVT-2026-01 §5，90 VAC / 滿載 / 40°C，量測保持時間 22 ms，符合 ≥20 ms。"/><p className="field-hint">至少 8 個字元。請記錄可追溯的證據；不適用時請說明原因。</p></div><p className="note-box">此記錄為你提供的審查判定。規格變更後會標記「需重審」，不會自動沿用通過狀態。</p><DialogFooter><Button variant="outline" onClick={()=>setEdit(null)}>取消</Button><Button disabled={note.trim().length<8||!valid} onClick={()=>{if(edit){onEvidence(edit.id,{verdict,method,note:note.trim(),specKey:fingerprint(project.spec),updatedAt:new Date().toISOString()});setEdit(null);}}}>儲存證據</Button></DialogFooter></DialogContent></Dialog></>;
}
