'use client';
import {useCallback,useEffect,useRef,useState,type CSSProperties} from 'react';
import {Activity,ArrowRight,BookOpen,Check,CircleHelp,Copy,Download,ExternalLink,FileJson,FolderOpen,Code2,LayoutDashboard,LoaderCircle,Plus,ShieldCheck,SlidersHorizontal,Upload,Zap} from 'lucide-react';
import {toast,Toaster} from 'sonner';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Sidebar,SidebarContent,SidebarFooter,SidebarHeader,SidebarInset,SidebarMenu,SidebarMenuButton,SidebarMenuItem,SidebarProvider,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {newProject,projectId,projectSchema,specSchema,ENGINE_VERSION,fingerprint,type Project,type Spec,type Result,type Evidence} from '@/lib/power/model';
import {downloadText,reportHtml} from '@/lib/power/report';
import {Dashboard} from './dashboard';
import {SpecEditor,type SpecChange} from './spec-editor';
import {sources,domains} from '@/lib/power/catalog';
import {Reviews} from './reviews';
import {Sources,Guide,GITHUB} from './resources';
import {Comparison} from './comparison';
import {Designer} from './designer';
import {requestCalculation} from './client-api';
import {usePowerTools} from './webmcp';
import {STORAGE_KEY as STORAGE,readWorkspace,writeWorkspace} from '@/lib/power/storage';
function SideNav({tab,onTab,onNew}:{tab:string;onTab:(s:string)=>void;onNew:()=>void}){
 const {setOpenMobile}=useSidebar();function nav(s:string){onTab(s);setOpenMobile(false);}
 return <Sidebar className="app-sidebar"><SidebarHeader><a className="brand" href="#" onClick={e=>{e.preventDefault();nav('overview');}}><div className="brand-symbol"><Zap size={24} fill="currentColor"/></div><div>POWER<span>DESIGN 360</span></div></a><div className="workspace-tag"><span/>ENGINEERING WORKSPACE</div></SidebarHeader><SidebarContent><div className="nav-label">設計空間</div><SidebarMenu>{[{id:'design',label:'逐步設計',icon:Zap},{id:'overview',label:'設計工作台',icon:LayoutDashboard},{id:'spec',label:'進階參數',icon:SlidersHorizontal},{id:'review',label:'360° 設計檢核',icon:ShieldCheck},{id:'compare',label:'方案比較',icon:Copy}].map(i=><SidebarMenuItem key={i.id}><SidebarMenuButton isActive={tab===i.id} onClick={()=>nav(i.id)}><i.icon/><span>{i.label}</span>{tab===i.id&&<span className="nav-dot"/>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="nav-label nav-label-second">知識與資源</div><SidebarMenu><SidebarMenuItem><SidebarMenuButton isActive={tab==='sources'} onClick={()=>nav('sources')}><BookOpen/><span>原廠參考資料</span><span className="nav-count">{sources.length}</span></SidebarMenuButton></SidebarMenuItem><SidebarMenuItem><SidebarMenuButton isActive={tab==='guide'} onClick={()=>nav('guide')}><CircleHelp/><span>模型與使用說明</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu><div className="sidebar-callout"><div className="mini-icon"><Activity size={19}/></div><h3>把想法，變成可驗證的設計</h3><p>從第一個參數，到完整設計審查。</p><Button onClick={onNew} className="sidebar-new"><Plus size={16}/>建立設計專案</Button></div></SidebarContent><SidebarFooter><a href={GITHUB} target="_blank" rel="noreferrer" className="github-link"><Code2 size={17}/><span>查看原始碼</span><ExternalLink size={13}/></a><div className="sidebar-version"><span className="version-dot"/>Power Design 360<span>v{ENGINE_VERSION}</span></div></SidebarFooter></Sidebar>;
}
export function Workbench({apiBase=''}:{apiBase?:string}){
 const [projects,setProjects]=useState<Project[]>([]),[activeId,setActiveId]=useState(''),[ready,setReady]=useState(false),[tab,setTab]=useState('design');
 const [result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[storageError,setStorageError]=useState('');
 const [newOpen,setNewOpen]=useState(false),[newName,setNewName]=useState(''),[newTopology,setNewTopology]=useState<Spec['topology']>('hwllc'),[renameOpen,setRenameOpen]=useState(false),[rename,setRename]=useState('');
 const savedSnapshot=useRef<string|null>(null);
 const uploadRef=useRef<HTMLInputElement>(null),seq=useRef(0),abortRef=useRef<AbortController|null>(null);
 const project=projects.find(p=>p.id===activeId)??projects[0];
 const parsed=project?specSchema.safeParse(project.spec):null;const key=parsed?.success?fingerprint(parsed.data):'';const current=result?.fingerprint===key?result:null;
 const issues:Record<string,string>=parsed&&!parsed.success?Object.fromEntries(parsed.error.issues.map(i=>[i.path[0],i.message])):{};
 const run=useCallback(async(p:Project)=>{
  const parsed=specSchema.safeParse(p.spec);if(!parsed.success){toast.error('請先修正參數範圍與上下限。');setTab('spec');return;}
  const n=++seq.current;abortRef.current?.abort();const controller=new AbortController();abortRef.current=controller;setBusy(true);setError('');const timeout=setTimeout(()=>controller.abort(),15000);
  try{const r=await requestCalculation(parsed.data,apiBase,controller.signal);if(n===seq.current){setResult(r);return r;}}catch(e){if(n===seq.current){setResult(null);setError(e instanceof Error&&e.name==='AbortError'?'計算連線逾時，請重新執行。':e instanceof Error?e.message:'計算服務無法使用。');}}finally{clearTimeout(timeout);if(n===seq.current)setBusy(false);}
 },[apiBase]);
 usePowerTools(project,current,run);
 useEffect(()=>{let initial:Project[]=[],selected='';try{const text=localStorage.getItem(STORAGE);savedSnapshot.current=text;const data=readWorkspace(text);initial=data.projects;selected=data.activeId;}catch{setStorageError('無法讀取原有專案。本次使用暫存專案，請匯出 JSON 保存資料。');}if(!initial.length)initial=[newProject(undefined,'hwllc')];const p=initial.find(p=>p.id===selected)??initial[0];setProjects(initial);setActiveId(p.id);setReady(true);void run(p);return()=>abortRef.current?.abort();},[run]);
 useEffect(()=>{if(!ready||!projects.every(p=>projectSchema.safeParse(p).success)||storageError)return;try{savedSnapshot.current=writeWorkspace(localStorage,savedSnapshot.current,{projects,activeId});}catch(e){setStorageError(e instanceof Error&&e.message==='STORAGE_CONFLICT'?'另一個分頁已更新資料。請先匯出目前修改，再重新整理；已暫停自動儲存以避免覆蓋。':'無法自動儲存，請立即匯出 JSON 保存目前專案。');}},[projects,activeId,ready,storageError]);
 useEffect(()=>{const changed=(e:StorageEvent)=>{if((e.key===STORAGE||e.key===null)&&e.newValue!==savedSnapshot.current)setStorageError('另一個分頁已更新資料。請先匯出目前修改，再重新整理；已暫停自動儲存以避免覆蓋。');};window.addEventListener('storage',changed);return()=>window.removeEventListener('storage',changed);},[]);
 function invalidate(){seq.current++;abortRef.current?.abort();setBusy(false);setResult(null);setError('');}
 function updateProject(change:(p:Project)=>Project){setProjects(list=>list.map(p=>p.id===project?.id?{...change(p),updatedAt:new Date().toISOString()}:p));}
 const editSpec:SpecChange=(field,value)=>{if((field==='topology'||field==='rectifier')&&!parsed?.success){toast.error('請先修正目前的無效欄位，再切換拓樸或整流級。');return;}invalidate();updateProject(p=>({...p,spec:{...p.spec,[field]:value}}));};
 function switchProject(id:string){if(!parsed?.success){toast.error('請先修正目前專案的無效參數。');return;}const p=projects.find(p=>p.id===id);if(p){invalidate();setActiveId(id);void run(p);}}
 function add(p:Project){if(projects.length>=30){toast.error('目前最多保存 30 個專案。');return false;}if(project&&!parsed?.success){toast.error('請先修正目前專案的無效參數。');return false;}invalidate();setProjects(list=>[...list,p]);setActiveId(p.id);setTab('overview');void run(p);return true;}
 async function importFile(file?:File){if(!file)return;try{if(file.size>1_000_000)throw new Error('檔案不得超過 1 MB。');const p=projectSchema.parse(JSON.parse(await file.text()));if(add({...p,id:projectId(),name:`${p.name.slice(0,70)}（匯入）`}))toast.success('已讀取專案 JSON。');}catch(e){toast.error(e instanceof Error&&e.message==='檔案不得超過 1 MB。'?e.message:'匯入失敗：檔案格式或參數不符合此版本。');}finally{if(uploadRef.current)uploadRef.current.value='';}}
 function exportProject(){if(!project)return;const p=projectSchema.safeParse(project);if(!p.success){toast.error('請先修正無效參數，再匯出專案。');return;}downloadText('power-design-project.json',JSON.stringify(p.data,null,2),'application/json');toast.success('已匯出可編輯的專案 JSON。');}
 if(!ready||!project)return <div className="boot-screen"><div className="brand-symbol"><Zap size={28}/></div><strong>Power Design 360</strong><p>準備你的設計工作台…</p></div>;
 const titles:Record<string,[string,string]>={design:['逐步設計','從輸入與輸出需求，自動建立第一輪元件方案。'],overview:['設計工作台','從規格到驗證，掌握每一個設計決策。'],spec:['進階參數','建立明確邊界，讓每一次計算都有依據。'],review:['360° 設計檢核','把全方位考量，落實為可追溯的工程證據。'],compare:['方案比較','比較設計取捨，保留你的決策過程。'],sources:['原廠參考資料','來自可信來源的設計方法與版本資訊。'],guide:['模型與使用說明','了解計算假設、資料保存與工程邊界。']};
 return <SidebarProvider style={{'--sidebar-width':'244px'} as CSSProperties}><SideNav tab={tab} onTab={setTab} onNew={()=>setTab('design')}/><SidebarInset className="app-main"><header className="app-topbar"><div className="breadcrumb"><SidebarTrigger className="mobile-trigger"/><FolderOpen size={16}/><span>我的設計空間</span><span className="breadcrumb-slash">/</span><strong>{tab==='design'?'建立新設計':project.name}</strong></div><div className="topbar-right"><span className="save-indicator"><span className={storageError||!parsed?.success?'dot-warn':'dot-good'}/>{tab==='design'?'草稿保留於此分頁':storageError?'暫存模式':!parsed?.success?'參數待修正':'儲存於此瀏覽器'}</span><span className="avatar">PD</span></div></header><div className="content-area"><div className="page-heading"><div><div className="eyebrow">POWER DESIGN WORKSPACE</div><h1>{titles[tab][0]}</h1><p>{titles[tab][1]}</p></div>{tab!=='design'&&<div className="heading-actions"><Button variant="outline" onClick={()=>{if(current){downloadText('power-design-report.html',reportHtml(project,current),'text/html;charset=utf-8');toast.success('報告已下載，可用瀏覽器開啟並列印為 PDF。');}}} disabled={!current||busy}><Download size={16}/>匯出報告</Button><Button className="calculate-button" onClick={()=>void run(project)} disabled={busy}>{busy?<LoaderCircle size={16} className="animate-spin"/>:<Zap size={16}/>} {busy?'計算中…':'執行計算'}</Button></div>}</div>
 {storageError&&<p className="error-banner" role="alert">{storageError}</p>}{error&&<div className="error-banner" role="alert">{error}<Button size="sm" variant="outline" onClick={()=>void run(project)}>重試</Button></div>}
 {tab!=='design'&&<section className="project-strip"><div className="project-icon"><SlidersHorizontal size={22}/></div><div className="project-picker"><label htmlFor="project-picker">目前專案</label><Select value={project.id} onValueChange={switchProject}><SelectTrigger id="project-picker" aria-label="選擇專案"><SelectValue/></SelectTrigger><SelectContent>{projects.map(p=><SelectItem value={p.id} key={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></div><span className="topology-label">{project.spec.topology==='hwllc'?'PFC + HWLLC':'PFC + LLC'}</span><div className="project-actions"><Button variant="ghost" size="sm" onClick={()=>{setRename(project.name);setRenameOpen(true);}}>重新命名</Button><Button variant="ghost" size="sm" onClick={()=>{if(projectSchema.safeParse(project).success)add({...project,id:projectId(),name:`${project.name.slice(0,70)}（副本）`,evidence:{}});else toast.error('請先修正參數。');}}><Copy size={14}/>複製</Button><Button variant="ghost" size="sm" onClick={exportProject}><FileJson size={14}/>JSON</Button><Button variant="ghost" size="sm" onClick={()=>uploadRef.current?.click()}><Upload size={14}/>匯入</Button><Button variant="outline" size="sm" onClick={()=>setTab('design')}><Plus size={14}/>新專案</Button></div><input ref={uploadRef} className="hidden" type="file" accept="application/json,.json" aria-label="匯入專案 JSON" onChange={e=>void importFile(e.target.files?.[0])}/></section>}
 {['overview','spec','review','compare'].includes(tab)&&<Tabs value={tab} onValueChange={setTab} className="workspace-tabs"><TabsList variant="line"><TabsTrigger value="overview">設計總覽</TabsTrigger><TabsTrigger value="spec">進階參數</TabsTrigger><TabsTrigger value="review">360° 檢核 <span>{domains.reduce((n,d)=>n+d.items.length,0)}</span></TabsTrigger><TabsTrigger value="compare">方案比較</TabsTrigger></TabsList></Tabs>}
 {!current&&!busy&&!error&&['overview','spec'].includes(tab)&&<div className="draft-banner"><Activity size={16}/>參數已變更，請執行計算以更新結果。</div>}
 <div hidden={tab!=='design'}><Designer apiBase={apiBase} onApply={add}/></div>
 {tab==='overview'&&<Dashboard project={project} result={current} onTab={setTab}/>}
 {tab==='spec'&&<><Button variant="outline" className="mb-4" onClick={()=>{setNewName('');setNewOpen(true);}}>從進階範本建立（含一般 LLC）</Button><div className="spec-notice"><ShieldCheck size={18}/><span>參數修改會使舊證據標記為「需重審」。效率與 PF 為假設，請用量測持續修正。</span></div><SpecEditor spec={project.spec} onChange={editSpec} issues={issues}/><div className="form-bottom"><p>{Object.keys(issues).length?`${Object.keys(issues).length} 個欄位需修正`:'數值修改自動儲存，按下按鈕更新解析結果。'}</p><Button disabled={busy||!parsed?.success} onClick={()=>void run(project)}><Zap size={16}/>執行計算</Button></div>{current&&<div className="success-banner"><Check size={17}/>計算完成。<Button variant="link" onClick={()=>setTab('overview')}>查看設計總覽 <ArrowRight size={15}/></Button></div>}</>}
 {tab==='review'&&<Reviews project={project} onEvidence={(id:string,e:Evidence)=>{updateProject(p=>({...p,evidence:{...p.evidence,[id]:e}}));toast.success('證據已記錄，綁定目前規格版本。');}}/>}
 {tab==='compare'&&<Comparison key={projects.map(p=>p.updatedAt).join()} projects={projects} apiBase={apiBase}/>}{tab==='sources'&&<Sources/>}{tab==='guide'&&<Guide/>}
 <footer className="workspace-footer"><span>POWER DESIGN 360 <i>·</i> v{ENGINE_VERSION}</span><span><span className="footer-dot"/>{tab==='design'?'逐步設計 · 自動選值':busy?'正在連線計算':current?'伺服器解析計算已完成':'等待執行計算'}<i>·</i>解析結果需經實機驗證</span></footer></div></SidebarInset>
 <Dialog open={newOpen} onOpenChange={setNewOpen}><DialogContent><DialogHeader><DialogTitle>建立新的設計專案</DialogTitle><DialogDescription>選擇起始範本，再依實機修改。示範值不代表你的實際設計。</DialogDescription></DialogHeader><div className="field"><label htmlFor="new-topology">起始範本</label><Select value={newTopology} onValueChange={v=>setNewTopology(v as Spec['topology'])}><SelectTrigger id="new-topology" className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="hwllc">240 W · 主動橋＋HWLLC＋單埠 PD</SelectItem><SelectItem value="llc-center-tapped">480 W · 一般半橋 LLC＋DC 輸出</SelectItem></SelectContent></Select></div><div className="field"><label htmlFor="project-name">專案名稱</label><Input autoFocus id="project-name" placeholder="例如：48 V 工業電源 EVT" maxLength={80} value={newName} onChange={e=>setNewName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&newName.trim()&&add(newProject(newName.trim(),newTopology)))setNewOpen(false);}}/></div><DialogFooter><Button variant="outline" onClick={()=>setNewOpen(false)}>取消</Button><Button disabled={!newName.trim()} onClick={()=>{if(add(newProject(newName.trim(),newTopology)))setNewOpen(false);}}>建立專案</Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={renameOpen} onOpenChange={setRenameOpen}><DialogContent><DialogHeader><DialogTitle>重新命名專案</DialogTitle><DialogDescription>名稱用於辨識方案，不影響計算參數。</DialogDescription></DialogHeader><Input aria-label="新專案名稱" maxLength={80} value={rename} onChange={e=>setRename(e.target.value)}/><DialogFooter><Button disabled={!rename.trim()} onClick={()=>{updateProject(p=>({...p,name:rename.trim()}));setRenameOpen(false);}}>儲存名稱</Button></DialogFooter></DialogContent></Dialog><Toaster position="bottom-right" richColors closeButton/></SidebarProvider>;
}
